### ISSUE TITLE
Bug? sethue can't be before background

### ISSUE THREAD

**Issue by Wikunia** [JuliaGraphics/Luxor.jl#103]
It seems like `sethue` can't be set before `background`.

@thecedarprince and me were wondering whether we missed something in the documentation and also why this appears to happen.

Example:
```
d = Drawing(400, 200, "test.png")
background("white")
sethue("black")
text("abc)
finish()
preview()
```

works as expected but
```
d = Drawing(400, 200, "test.png")
sethue("black")
background("white")
text("abc)
finish()
preview()
```

shows only the white background.

**Comment by cormullion** [comment]
I think 'background()` is just 

```
setcolor(col)
paint()
- return this new color 
```

so you're just overwriting "black" with "white". I suppose you could stash the current color, paint(), and then unstash. But it seemed obvious that you have to paint the wall before painting a mural... :)

**Comment by Wikunia** [comment]
Haha okay. Yeah it makes kinda sense. I think it's quite normal to use `background` first and `sethue` afterwards.
We were just a little confused when we accidentally had it the other way around.

**Comment by TheCedarPrince** [comment]
Ah! Thanks for clarifying this @cormullion ! Is this documented? If not, I'd be happy to open a docs PR to add a line in about this. :smile:

**Comment by cormullion** [comment]
Well, who reads documentation? Anyway, Luxor docs are way too big now. 🤣

Instead, `background()` can preserve the current state. [added to master](https://github.com/JuliaGraphics/Luxor.jl/commit/b145f3d36b657c5bc04992126623e0219e33d384)
