### ISSUE TITLE
`background` goes wrong when `Drawing` non-square

### ISSUE THREAD

**Issue by guo-yong-zhi** [JuliaGraphics/Luxor.jl#106]
```julia
m = @imagematrix begin
background(1,1,1)
end 1 2
```
```julia
m |> show
ARGB32[ARGB32(1.0N0f8,1.0N0f8,1.0N0f8,1.0N0f8); ARGB32(0.0N0f8,0.0N0f8,0.0N0f8,0.0N0f8)]
```

**Comment by cormullion** [comment]
Version?

**Comment by guo-yong-zhi** [comment]
> 
> 
> Version?

Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6146 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = https://mirrors.bfsu.edu.cn/julia/static

Status `~/.julia/environments/v1.5/Project.toml`
  [336ed68f] CSV v0.7.5
  [5ae59095] Colors v0.12.3
  [a93c6f00] DataFrames v0.21.5
  [7073ff75] IJulia v1.21.2
  [6218d12a] ImageMagick v1.1.5
  [916415d5] Images v0.22.4
  [ae8d54c2] Luxor v2.2.1
  [91a5bcdd] Plots v1.5.7
  [295af30f] Revise v2.7.3

**Comment by cormullion** [comment]
Try updating Luxor to the current version?

**Comment by guo-yong-zhi** [comment]
OK with Luxor v2.3.0. Thx :)
