### ISSUE TITLE
 Inconsistent transparent background

### ISSUE THREAD

**Issue by guo-yong-zhi** [JuliaGraphics/Luxor.jl#107]
```julia
using Luxor
bgcolor = ARGB32(1,1,1,0)
m = @imagematrix begin
background(bgcolor)
    end 3 5
@show bgcolor m[1] bgcolor==m[1]
```
```julia
bgcolor = ARGB32(1.0N0f8,1.0N0f8,1.0N0f8,0.0N0f8)
m[1] = ARGB32(0.0N0f8,0.0N0f8,0.0N0f8,0.0N0f8)
bgcolor == m[1] = false
```

**Comment by guo-yong-zhi** [comment]
And version:
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Xeon(R) Gold 6146 CPU @ 3.20GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_PKG_SERVER = https://mirrors.bfsu.edu.cn/julia/static

Status `~/.julia/environments/v1.5/Project.toml`
  [35d6a980] ColorSchemes v3.9.0
  [5ae59095] Colors v0.12.3
  [861a8166] Combinatorics v1.0.2
  [7073ff75] IJulia v1.21.2
  [6218d12a] ImageMagick v1.1.5
  [916415d5] Images v0.22.4
  [ae8d54c2] Luxor v2.3.0
  [91a5bcdd] Plots v1.5.7
  [295af30f] Revise v2.7.3

**Comment by cormullion** [comment]
Hi again! I think I've fixed this issue on master, but I'd welcome a bit of testing, because I got very confused with alphas and ARGBs and the order of the colours... etc. The change may change some older code.

**Comment by cormullion** [comment]
fixed in 2.4.0?

**Comment by guo-yong-zhi** [comment]
> fixed in 2.4.0?

Yes! Thanks!

**Comment by guo-yong-zhi** [comment]
but ....
```julia
using Luxor
using Colors
bgcolor = ARGB32(0,0,0,0)
m = @imagematrix begin
background(bgcolor)
    end 3 5
@show bgcolor m[1] bgcolor==m[1]
```  

```
bgcolor = ARGB32(0.0N0f8,0.0N0f8,0.0N0f8,0.0N0f8)
m[1] = ARGB32(1.0N0f8,1.0N0f8,1.0N0f8,0.0N0f8)
bgcolor == m[1] = false
```
version:
```
  [35d6a980] ColorSchemes v3.9.0
  [5ae59095] Colors v0.12.3
  [861a8166] Combinatorics v1.0.2
  [6218d12a] ImageMagick v1.1.5
  [ae8d54c2] Luxor v2.4.0
  [de0858da] Printf
  [9a3f8284] Random
```

**Comment by cormullion** [comment]
Oh, pity... :(

I'm not sure if I can fix this. It seems like you can't specify a transparent black background for the image matrix explicitly, although you can have a transparent white one?

Until it's fixed, it would be better to use Images.jl if you want explicit control over pixels...

If you have any suggestions, let me know! :)

**Comment by guo-yong-zhi** [comment]
Can you make the return value be consistent with the actual background color?
```julia
using Luxor
using Colors
bgcolor = ARGB32(0,1,0,0)
m = @imagematrix begin
returnbc = background(bgcolor)
    end 3 5
@show bgcolor m[1] bgcolor==m[1] returnbc ARGB32(returnbc...)==m[1]
```

```
bgcolor = ARGB32(0.0N0f8,1.0N0f8,0.0N0f8,0.0N0f8)
m[1] = ARGB32(1.0N0f8,1.0N0f8,1.0N0f8,0.0N0f8)
bgcolor == m[1] = false
returnbc = (0.0, 1.0, 0.0, 0.0)
ARGB32(returnbc...) == m[1] = false
```

**Comment by cormullion** [comment]
Luxor's built around RGBA  - the sethue/setcolor thing works with the four RGBA float64 values... 

```
using Luxor, Colors

Drawing(4, 4)
    origin()
    returnbg = background("green")
    sethue("red")
    box(O, 2, 2, :fill)
    m = image_as_matrix()
finish()

parse(Colorant, m[1]) == RGBA(returnbg...)

=> true
```

I'm thinking that if you want to use ARGB32 and pixel values with a bit more precision and control, you could try using Cairo.jl - I haven't found a way to make both your examples work.

**Comment by guo-yong-zhi** [comment]
> Luxor's built around RGBA - the sethue/setcolor thing works with the four RGBA float64 values...
> 
> ```
> using Luxor, Colors
> 
> Drawing(4, 4)
>     origin()
>     returnbg = background("green")
>     sethue("red")
>     box(O, 2, 2, :fill)
>     m = image_as_matrix()
> finish()
> 
> parse(Colorant, m[1]) == RGBA(returnbg...)
> 
> => true
> ```
> 
> I'm thinking that if you want to use ARGB32 and pixel values with a bit more precision and control, you could try using Cairo.jl - I haven't found a way to make both your examples work.

```julia
using Luxor, Colors

Drawing(4, 4)
    origin()
    returnbg = background(0,1,0,0)
    sethue("red")
    box(O, 2, 2, :fill)
    m = image_as_matrix()
finish()

parse(Colorant, m[1]) == RGBA(returnbg...)
=>false
```
it's not about type but about transparence. 
And, thanks for your advice.

**Comment by cormullion** [comment]
I've changed this part of the code for this for the next release of Luxor.  The problem was I think something to do with "premultiplied alpha"/"alpha divide". The imagematrix functions now return arrays of 4 floats, instead of UInt32s.

```
julia> m = @imagematrix begin
               background("red")
           end 2 2
2×2 Array{Array{Float64,1},2}:
 [1.0, 0.0, 0.0, 1.0]  [1.0, 0.0, 0.0, 1.0]
 [1.0, 0.0, 0.0, 1.0]  [1.0, 0.0, 0.0, 1.0]
```

The default matrix is transparent black:

```
julia> m = @imagematrix begin
               
           end 2 2
2×2 Array{Array{Float64,1},2}:
 [0.0, 0.0, 0.0, 0.0]  [0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0]  [0.0, 0.0, 0.0, 0.0]
```

julia>  m = @imagematrix begin
               background(1, 1, 0, 0.5)
       end 2 2
2×2 Array{Array{Float64,1},2}:
 [1.0, 1.0, 0.0, 0.501961]  [1.0, 1.0, 0.0, 0.501961]
 [1.0, 1.0, 0.0, 0.501961]  [1.0, 1.0, 0.0, 0.501961]

The only thing you can't do is set a completely transparent background:

```
julia> m = @imagematrix begin
                  bgcolor = background(RGBA(1, 1, 1, 0))
           end 2 2
2×2 Array{Array{Float64,1},2}:
 [0.0, 0.0, 0.0, 0.0]  [0.0, 0.0, 0.0, 0.0]
 [0.0, 0.0, 0.0, 0.0]  [0.0, 0.0, 0.0, 0.0]
```

 I think this is because the information is lost when Cairo transfers the RGBASurface ImageSurface, because everything is multiplied by the alpha. 0.0.

`imagematrix` now does an alphadivide on the matrix, which takes a few milliseconds. Since I didn't want to reverse the operation at the end, the return type is now an Array of Arrays, easier to use later I expect, rather than the array of UInt32s... Hence the incompatible change.

A small problem that this introduces is that there are now some rounding errors, as the divisions of UInt8s by alpha aren't always exact.

```
m = @imagematrix begin
                  bgcolor = background(RGBA(0.5, 0, 0))
           end 2 2
2×2 Array{Array{Float64,1},2}:
 [0.501961, 0.0, 0.0, 1.0]  [0.501961, 0.0, 0.0, 1.0]
 [0.501961, 0.0, 0.0, 1.0]  [0.501961, 0.0, 0.0, 1.0]
```

Difference in values can be up to about 0.025.

If you want to give this a spin it's on master.

**Comment by guo-yong-zhi** [comment]
I think that keeping `imagematrix` to be a Array of `Colorant` is better since we depending on package `Colors`. The rounding problem should be left to `Colors`. As for transparent inconsistent problem, how about simply returning a regular form of  transparent color? Say, if the alpha of input color is 0, the `background` just return (0,0,0,0). I think that also make sense, and easy to fix.

**Comment by cormullion** [comment]
Originally, for performance reasons, I didn't want to have to convert from Uint32 to RGBA then back again... Do you think there's no need to do this alphadivide process at all? I could revert it. 

I could add something to `background()` as a special case, but it introduces some unpredictable behaviour:

```
@draw begin
    r, g, b, a = background(1, 1, 0.5, 0)
    sethue(r, g, b)
    box(O, 100, 100, :fill)
end
```

we wouldn't expect r, g, b to not be 1, 1, 0.5...?

**Comment by guo-yong-zhi** [comment]
I prefer background's return value being consistent with m[1] (actural color in imagematrix) than being consistent with input. In Luxor v2.4.0, the typeof `imagematrix` is `Base.ReinterpretArray{ARGB32,2,ARGB32,Array{ARGB32,2}}`, a Array of Colorant. If making input&return&actural color all consistent at the cost of `imagematrix` type degeneration. I don't think it's worth that much. :)

**Comment by cormullion** [comment]
OK, no worries - I'll leave all the alphamultiplying code out, and go back to ARGB32. Users will have to do the necessary adjustments in their own code...

If you could submit a PR to show how the `background()` function should combine the various requirements, I'd be very grateful! 

Thanks!

**Comment by cormullion** [comment]
@Wikunia @TheCedarPrince I'll link you to this issue just in case you're interested ... :)

**Comment by guo-yong-zhi** [comment]
> 
> 
> OK, no worries - I'll leave all the alphamultiplying code out, and go back to ARGB32. Users will have to do the necessary adjustments in their own code...
> 
> If you could submit a PR to show how the `background()` function should combine the various requirements, I'd be very grateful!
> 
> Thanks!

here is the problem. I am new to GitHub. I have no idea of how PR works

**Comment by cormullion** [comment]
No worries - and no hurry!

**Comment by TheCedarPrince** [comment]
If you want me to test anything or feedback on anything here, feel free to ping me @cormullion ! I like the approach you are taking. :smile:
