### ISSUE TITLE
Specifying Circle Sector Centerpoint 

### ISSUE THREAD

**Issue by jessebett** [JuliaGraphics/Luxor.jl#11]
The `Luxor.sector` function draws sectors centered at the current origin:
`sector(innerradius, outerradius, startangle, endangle, action=:none)`

This feels inconsistent with the other Circles, Ellipses, and other Survey Things which take the center point as their first argument:
`circle(pt, r, action)`
`circlepath(center::Point, radius, action=:none;
    reversepath=false,
    kappa = 0.5522847)`

Is it possible to change sector to also take a centerpoint argument?
Or is there another method to draw circle sectors about points other than the origin?

Edit: `arc` function is working for thin arcs about cpt, but I think I'd also like sectors about cpt

**Comment by cormullion** [comment]
Hi @jessebett I'll have a look. It should be possible to add an additional method that takes a `Point` first argument. It can then temporarily. relocate to that point for drawing business...

**Comment by cormullion** [comment]
The [latest commit](https://github.com/JuliaGraphics/Luxor.jl/commit/17f05c5ae7b770c832aefbaf1af366639f79d957) has some additional methods for `sector()`. I'll get round to tagging a new release later this month, probably, if it looks OK.

**Comment by jessebett** [comment]
Thanks @cormullion! (wow, that is much simpler than the solution I was trying for)

Yes, I noticed there's some inconsistency with functions taking `Point` and functions taking `x, y` as their first argument(s). 
 
Either way I'm really loving Luxor so far! Thanks for your work!

**Comment by cormullion** [comment]
@jessebett cool. You can Pkg.checkout until I get round to tagging, I hope.

When I first started trying to avoid using  Cairo directly, it was all x and y. Gradually I shifted to Points, but it's all a learning curve. :)
