### ISSUE TITLE
scale(0.0) leaks outside the layer

### ISSUE THREAD

**Issue by Wikunia** [JuliaGraphics/Luxor.jl#114]
## Example

```
using Luxor

@png begin
    @layer begin
        scale(0.0)
        circle(O, 50, :fill)
    end
    @layer begin
        circle(Point(100, 100), 50, :fill)
    end
end
```

I think this should show the second circle at `Point(100, 100)` but it doesn't because it gets also scaled to 0.

Interestingly enough:
```julia
using Luxor

@png begin
    @layer begin
        scale(0.5)
        circle(O, 50, :fill)
    end
    @layer begin
        circle(Point(100, 100), 50, :fill)
    end
end
```

this works. It only fails when scaling down to 0 which doesn't happen inside a single frame but can happen in an animation.

**Comment by cormullion** [comment]
Weird - I don't think Luxor is doing anything here:

```
scale(f::Real) = Cairo.scale(get_current_cr(), f, f)
```

In fact, even this doesn't work:

```
@draw begin
    scale(0.0)
    circle(O, 50, :fill)
    scale(1)
    circle(Point(100, 100), 50, :fill)
end
```

It's like Cairo doesn't like `scale(0.0)`.

**Comment by Wikunia** [comment]
yeah so what `scale(1)` does is it scales it by 1 not to 1 so that can't work.
I assume Cairo doesn't like `scale(0.0)` which also makes kind of sense. Is just annoying for Javis :smile:

**Comment by cormullion** [comment]
So if you ever do `scale(0.0)` you're stranded for ever... ? Yikes... ;)

**Comment by Wikunia** [comment]
Exactly :joy:

**Comment by cormullion** [comment]
```
function scale(f::Real)
    if !iszero(f)
        Cairo.scale(get_current_cr(), f, f)
    end
end
``` 
?

**Comment by Wikunia** [comment]
Works but otherwise throw a warning or something.
