### ISSUE TITLE
`@imagematrix` add a  `@imagematrix!`

### ISSUE THREAD

**Issue by xiaodaigh** [JuliaGraphics/Luxor.jl#115]
The ` @imagematrix` macro seems to require a fresh buffer each time. If I use it a lot (like in a loop) then it increases allocations alot.

Add a  `@imagematrix!`

```
@imagematrix! buffer begin
   ...
end
```

where can re-use `buffer` by drawing into it.

**Comment by cormullion** [comment]
Sounds like a good idea!

**Comment by cormullion** [comment]
I made a branch (https://github.com/JuliaGraphics/Luxor.jl/tree/cormullion/imbuffer) that implements this - not sure how to measure any change in allocations though. I think I see a reduction, but not sure what Cairo is up to sometimes.

```
using Luxor
w = 16
h = 10
buffer = zeros(UInt32, w, h)
Drawing(w, h, :image)
background("blue")
origin()
sethue("rebeccapurple")
text("hello", O)
m1 = image_as_matrix!(buffer)
finish()
m1

-> 10×16 reinterpret(ColorTypes.ARGB32, ::Array{UInt32,2}):
```

You can reuse `buffer` again. 

Don't really understand this stuff, to be honest... :)

**Comment by xiaodaigh** [comment]
Doesn't seem to work 

```
@imagematrix! buffer begin
                background("grey10")
                fontsize(20)
                sethue("orange")
                g2.xd1 = y/70
                g2.xd2 = y/80
                g2.yd1 = y/90
                g2.yd2 = y/100
                g2.xp1 = 8y
                g2.xp2 = 4y
                g2.yp3 = 1y
                g2.yp4 = 3y
                drawguilloche(g2, 150,
                    npoints=300,
                    stepby=0.05,
                    limit=10,
                    colorfunction = (t) -> sethue(HSL(rescale(t, 0, 300, 0, 359), 0.9, 0.7)))
                t2 = time_ns()
                text(string("fps: ", round(1E9/(t2-t1), digits=2)),
                    boxtopleft(BoundingBox() * 0.9))
            end
```

**Comment by cormullion** [comment]
Could you try an MWE, such as:

```
using Luxor, Images

w = h = 40
buffer = zeros(UInt32, w, h)
m = @imagematrix! buffer begin
        background("grey10")
        sethue("orange")
        circle(O, 20, :fill)
end 40 40

RGB.(m)
```
<img width="134" alt="Screenshot 2020-09-27 at 17 20 29" src="https://user-images.githubusercontent.com/52289/94370106-c5255100-00e5-11eb-9fb8-60f7a82ebbfc.png">

If this works, then you've got different problems with your code... :)

**Comment by xiaodaigh** [comment]
BTW it works.
