### ISSUE TITLE
In-memory drawing for Pluto

### ISSUE THREAD

**Issue by j-fu** [JuliaGraphics/Luxor.jl#116]
Hi, I just found the  advise posted by @cormullion in https://github.com/JuliaGraphics/Luxor.jl/issues/49#issuecomment-538900160_
```
macro draw(body, width=600, height=600)
    quote
        Drawing($width, $height, :png)
        origin()
        background("white")
        sethue("black")
        $(esc(body))
        finish()
        (isdefined(Main, :IJulia) && Main.IJulia.inited) ? jupyter = true : jupyter = false
        Juno.isactive() ? juno = true : juno = false
        if juno || jupyter
            display(CURRENTDRAWING[1])
        else
            @info "use Juno or Jupyter"
        end
    end
end
```
In Pluto the following worked, without creating temporary files:
````
function draw(f,width, height; file=:png)
        drawing=Drawing(width,height,file)
        origin()
        background("white")
        sethue("black")
        f()
        finish()
        drawing
end
````

````
draw(juliacircles,500,500)
````
Perhaps this is worth a PR ?
EDIT: added a file parameter.

**Comment by cormullion** [comment]
Hi there! In fact the `@draw` macro has changed since then (edited by fons himself, to work better with Pluto! - so perhaps a new `draw` function isn't needed?

**Comment by j-fu** [comment]
Hi, in fact this worked out of the box, which I still find amazing. However the current version of @draw writes a temp svg file to the disk each time the graphics becomes updated. With slider control from PlutoUI these files  become quite a lot... IMHO there should be an easy way (perhaps this even could be the default in the notebook case ?) to draw without intermediate files.

**Comment by cormullion** [comment]
That’s odd - could you share a short piece of code that does this?

**Comment by j-fu** [comment]
For creating the mwe I restarted and redid everything, the problem is  gone. Odd indeed, probably  my fault. Sorry for the trouble. At least this made me better understand Luxor, and gave me the impression that it is well supported. I plan to use it for teaching and  to give it in the hand of some students which should be able to realize some ideas of mine with Luxor and Pluto.

So this can be closed.
