### ISSUE TITLE
Thread-safety

### ISSUE THREAD

**Issue by tkf** [JuliaGraphics/Luxor.jl#117]
Since Luxor.jl uses a global array (as a stack?),

https://github.com/JuliaGraphics/Luxor.jl/blob/ba1965042642146f35afb3207d3592ee4beeea0e/src/drawings.jl#L44

I'm guessing that it is not thread-safe. Is this correct?

Can we make it thread-safe and async-safe by using a [context variable](https://github.com/tkf/ContextVariablesX.jl) (https://github.com/JuliaLang/julia/pull/35833) instead of the global?  I'm suspecting that something like `@png` can simply wrap [`with_context`](https://tkf.github.io/ContextVariablesX.jl/dev/#ContextVariablesX.with_context).  Or is Cairo.jl already non-thread-safe and so it's hard to make Luxor.jl parallelizable?

**Comment by cormullion** [comment]
Hello! Interesting questions, but I'm sorry I don't know the answer to any of them... I've never tried anything with threads.

`CURRENTDRAWING` is just a way to have a global to hold the current drawing - it's not used as a stack, really.

Cairo.jl does most of the important work, so it would definitely have a major say in whether anything can be parallelized.

**Comment by cancandan** [comment]
Minimum example that crashes the 1.7.2 julia repl:
```
using Luxor, Colors

function make_drawing()         
    buffer = rand(UInt32, 200, 200)
    Drawing(200, 200, :image)    
    setcolor(rand(), 0, 0, 0)
    poly([Point(1,10), Point(100,110), Point(50,50)], close=true, action=:fill)        
    m = image_as_matrix!(buffer)    
    finish()
    return m
end

Threads.@threads for i = 1:1000
    make_drawing()
end
```

Outputs errors like:

julia: cairo-path-fixed.c:366: _cairo_path_fixed_last_op: Assertion `buf->num_ops != 0' failed.

julia: cairo-path-fixed.c:392: _cairo_path_fixed_drop_line_to: Assertion `_cairo_path_fixed_last_op (path) == CAIRO_PATH_OP_LINE_TO' failed.

julia: cairo-path-fixed.c:382: _cairo_path_fixed_penultimate_point: Assertion `prev_buf->num_points >= 2 - buf->num_points' failed.

**Comment by cormullion** [comment]
It might be worth trying to create Cairo RGB surfaces in a Cairo.jl-only session in the same way. That way it would be possible to see whether it’s a Luxor problem or a Cairo.jl problem. If the former, I could think about how to fix it…

**Comment by cancandan** [comment]
Thanks. I have no idea how to do that though. Should I do as in the examples here https://github.com/JuliaGraphics/Cairo.jl/blob/master/samples/Samples.md ?

**Comment by cormullion** [comment]
Yes, that's what I'd do.

**Comment by cancandan** [comment]
I have turned the example on this page https://github.com/JuliaGraphics/Cairo.jl/blob/master/samples/sample_fill_and_stroke2.jl
to a function.

```
function multiple_threads_calling_this_func()
    c = CairoRGBSurface(256,256);
    cr = CairoContext(c);

    save(cr);
    set_source_rgb(cr,0.8,0.8,0.8);    # light gray
    rectangle(cr,0.0,0.0,256.0,256.0); # background
    fill(cr);
    restore(cr);

    save(cr);
    ## original example, following here
    move_to(cr, 128.0, 25.6);
    line_to(cr, 230.4, 230.4);
    rel_line_to(cr, -102.4, 0.0);
    curve_to(cr, 51.2, 230.4, 51.2, 128.0, 128.0, 128.0);
    close_path(cr);

    move_to(cr, 64.0, 25.6);
    rel_line_to(cr, 51.2, 51.2);
    rel_line_to(cr, -51.2, 51.2);
    rel_line_to(cr, -51.2, -51.2);
    close_path(cr);

    set_line_width(cr, 10.0);
    set_source_rgb(cr, 0, 0, 1);
    fill_preserve(cr);
    set_source_rgb(cr, 0, 0, 0);
    stroke(cr);

    ## mark picture with current date
    restore(cr);

    buffer = rand(UInt32, 256, 256)
    imagesurface = Cairo.CairoImageSurface(buffer, Cairo.FORMAT_ARGB32, flipxy=false)
    cr2 = Cairo.CairoContext(imagesurface)
    Cairo.set_source_surface(cr2, c, 0, 0)
    Cairo.paint(cr2)
    data = imagesurface.data
    Cairo.finish(imagesurface)
    Cairo.destroy(imagesurface)
    return reinterpret(ARGB32, permutedims(data, (2, 1)))
end
```

And then called it from multiple threads as shown:
```
Threads.@threads for i = 1:1000
    multiple_threads_calling_this_func()
end
```

No errors...

**Comment by cormullion** [comment]
Good work, and useful information! It looks like Luxor's simplified approach isn't thread-safe, whereas Cairo.jl is...

It's worth pointing out that Luxor is intended to be a simplified version of Cairo - the aim is to provide an easy way for users to draw simple colored graphics on a 2D drawing. For more advanced uses, most package developers use Cairo directly - looking at https://juliahub.com/ui/Packages/Cairo/l6vnT/1.0.5?page=2 there are hundreds of packages that interface directly with Cairo.jl. That may be the best course for your multi-threaded purposes here... Good luck!
