### ISSUE TITLE
IOError 

### ISSUE THREAD

**Issue by alnassirah** [JuliaGraphics/Luxor.jl#118]
I'm trying to run my first animation in Luxor, but I keep getting this error 

`IOError: could not spawn `ffmpeg -loglevel panic -f image2 -i /var/folders/2s/p1vy6rx91lsfh9ltgzz6j_lmb6r7gr/T/jl_WkZlnq/%10d.png -vf palettegen -y /var/folders/2s/p1vy6rx91lsfh9ltgzz6j_lmb6r7gr/T/jl_WkZlnq/test-palette.png`: no such file or directory (ENOENT)`

This happens with any program I try, I'm just copying the program in the tutorial page 

`	demo = Movie(400, 400, "test")
	
	function backdrop(scene, framenumber)
	    background("black")
	end
	
	function frame(scene, framenumber)
	    sethue(Colors.HSV(framenumber, 1, 1))
	    eased_n = scene.easingfunction(framenumber, 0, 1, scene.framerange.stop)
	    circle(polar(100, -π/2 - (eased_n * 2π)), 80, :fill)
	    text(string("frame $framenumber of $(scene.framerange.stop)"),
	        Point(O.x, O.y-190),
	        halign=:center)
	    text(scene.opts,
	        boxbottomcenter(BoundingBox()),
	        halign=:center,
	        valign=:bottom)
	end
	
	animate(demo, [
	    Scene(demo, backdrop, 0:359),
	    Scene(demo, frame, 0:359,
	        easingfunction=easeinoutcubic,
	        optarg="made with Julia")
	    ],
	    creategif=true)`

**Comment by cormullion** [comment]
Hi! At the moment, this function assumes that you have ffmpeg installed and accessible from your current location. Try typing ffmpeg at the command line. One day I’ll add the relevant FFMPEG.jl package.

**Comment by alnassirah** [comment]
yes I just realized I don't have ffmpeg installed, closing this issue. 

Many thanks..
