### ISSUE TITLE
Integration with Interact.jl doesn't work

### ISSUE THREAD

**Issue by Sov-trotter** [JuliaGraphics/Luxor.jl#121]
So I have been using a few examples like the ones here https://github.com/JuliaGraphics/Luxor.jl/issues/27 and quite few others. The image and sliders both show up but there isn't any change in the image even if I change the slider value. Is this a known issue or a bug at my end?

**Comment by Sov-trotter** [comment]
Seems like there was some issue on my end. This works well.

**Comment by cormullion** [comment]
Thanks! To be honest, I've been finding Pluto a bit more useful for interactivity these days, and haven't used Interact for a while.

**Comment by Sov-trotter** [comment]
Yeah. These integrations are a bit tricky. I have been working on https://github.com/Wikunia/Javis.jl/issues/207 actually.

**Comment by cormullion** [comment]
Right. Getting all these things with different design goals to work together is quite a challenge...
