### ISSUE TITLE
Luxor v2.6.0 bug in text() alignment when angle parameter != 0

### ISSUE THREAD

**Issue by p2peditor** [JuliaGraphics/Luxor.jl#122]
The :center, :middle etc. alignments don't work right when the angle parameter is not zero. That is, for the use-case of trying to center some text on a target point but render the text on an angle, the text is placed correctly on the target point when the angle is 0, but for other angles the text moves some distance away from the target point. Further, the distance and direction seem to be correlated with the value of the angle parameter, such that the text "walks" in a circle around the target point.

Attached is some code and images to repro. The "zero_angle" image shows what you'd expect, text centered on the marker dots. The "var_angle" image shows what happens if you try to angle the text to match the lines. The difference in the code is literally just the presence or absence of the angle parameter to the text() call.
[text_align_repro.jl.txt](https://github.com/JuliaGraphics/Luxor.jl/files/5683529/text_align_repro.jl.txt)
![zero_angle](https://user-images.githubusercontent.com/17077875/101991236-2a59fe80-3c60-11eb-83cf-394a7409763c.png)
![var_angle](https://user-images.githubusercontent.com/17077875/101991237-2cbc5880-3c60-11eb-9295-aad8882d6ff8.png)

**Comment by cormullion** [comment]
Yes, good point. It didn't occur to me that both alignment and rotation could be wanted... 😂 

I'll investigate and see if it's easy to improve. For now, perhaps you could do the rotation in a separate "layer"...

**Comment by cormullion** [comment]
I hope this is fixed in the latest master. Perhaps if you could give it a try (go `] add Luxor#master `) - if there are no problems, I'll release it as v2.6.1.

**Comment by p2peditor** [comment]
That does appear to have fixed it. Awesome!
