### ISSUE TITLE
placing the results of @svg, @imagematrix with placeimage

### ISSUE THREAD

**Issue by guo-yong-zhi** [JuliaGraphics/Luxor.jl#134]
Now, we can `placeimage` from a file with `readpng` and `readsvg`. Can we do it in memory? 
Maybe something like placeimage(img::Array{ARGB32,2}, x, y) or placeimage(img::svg-object, x, y)

**Comment by cormullion** [comment]
Hi! Sounds like a good addition. I've added this to the current master, to see if it work.

```
using Luxor # master 

m1 = @imagematrix begin    
    juliacircles(10) 
end 40 40

# typeof(m1) = Base.ReinterpretArray{ARGB32, 2, UInt32, Matrix{UInt32}, false}

@draw begin
    for i in 1:50
        pos = rand(BoundingBox())
        @layer begin
            translate(pos)
            rotate(rand() * 2π)
            placeimage(m1, centered = rand(Bool))   # <-
        end
    end
end
``` 

<img width="380" alt="Screenshot 2021-01-20 at 11 46 59" src="https://user-images.githubusercontent.com/52289/105170698-3a91b300-5b15-11eb-9b46-719d4b9c58b0.png">

**Comment by guo-yong-zhi** [comment]
ah, something seems wrong
```julia
using Luxor # master 

m1 = @imagematrix begin    
    juliacircles(10) 
end 40 40

# typeof(m1) = Base.ReinterpretArray{ARGB32, 2, UInt32, Matrix{UInt32}, false}

@draw begin
    for i in 1:50
        pos = rand(BoundingBox())
        @layer begin
            translate(pos)
            rotate(rand() * 2π)
            placeimage(m1, centered = rand(Bool))   # <-
        end
    end
end
```
->  
>AssertionError: typeof(b) == Matrix{UInt32}
Stacktrace:
 [1] placeimage(::Base.ReinterpretArray{ColorTypes.ARGB32,2,UInt32,Array{UInt32,2}}, ::Point; centered::Bool) at C:\Users\abcde\.julia\packages\Luxor\acGuD\src\images.jl:148
 [2] macro expansion at .\In[3]:15 [inlined]
 [3] macro expansion at C:\Users\abcde\.julia\packages\Luxor\acGuD\src\basics.jl:503 [inlined]
 [4] macro expansion at .\In[3]:12 [inlined]
 [5] top-level scope at C:\Users\abcde\.julia\packages\Luxor\acGuD\src\drawings.jl:600
 [6] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1091

***
Julia Version 1.5.0
Commit 96786e22cc (2020-08-01 23:44 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
***
  [5ae59095] Colors v0.12.6
  [7073ff75] IJulia v1.23.1
  [916415d5] Images v0.23.3
  [ae8d54c2] Luxor v2.8.0 `https://github.com/JuliaGraphics/Luxor.jl.git#master`
***

**Comment by cormullion** [comment]
Ah... I'm running Julia v1.6 - it doesn't work on Julia v1.5 apparently, although I was expecting it to be compatible.  ¯\\\_(ツ)_/¯

**Comment by cormullion** [comment]
I've added a `collect()` and some type annotations, so I'm hoping it works with a few more Julia versions .... :)

**Comment by guo-yong-zhi** [comment]
hi,   @cormullion. I have submitted a pull request to fix that. Please check it. 
Furthermore, what about the `@svg` version? Is there a way to convert svg `Drawing` to `SVGimage`?

**Comment by cormullion** [comment]
>Furthermore, what about the @svg version? Is there a way to convert svg Drawing to SVGimage?

I don't know - I only know what Rsvg does at the moment. :)  What's your required workflow?

**Comment by guo-yong-zhi** [comment]
I want that:
```julia
using Luxor # master 

m1 = @svg begin    
    juliacircles(10) 
end 40 40

@draw begin
    for i in 1:50
        pos = rand(BoundingBox())
        @layer begin
            translate(pos)
            rotate(rand() * 2π)
            placeimage(MagicFunctionThatCanConvertDrawingToSVGimage(m1), centered = rand(Bool))   # <-
        end
    end
end
```

**Comment by cormullion** [comment]
Something like this perhaps:

```julia
using Luxor, Rsvg

function _readsvg_string(str)
    r = Rsvg.handle_new_from_data(str::AbstractString)

    if r.ptr == C_NULL
        throw(error("readsvg(): some error message "))
    end

    d = Rsvg.handle_get_dimensions(r)
    if iszero(d.width) || iszero(d.height)
        throw(error("readsvg(): can't get dimensions from this SVG image. Either it's not a valid SVG file, or the format is different from what I'm expecting."))
    end

    return Luxor.SVGimage(r, d.em, d.ex, d.width, d.height)
    SVGimage(r, d.em, d.ex, d.width, d.height)
end

m1 = Drawing(100, 100, :svg)
    origin()    
    juliacircles(10) 
    finish()

svgstring = String(m1.bufferdata)

@draw begin
    for i in 1:50
        pos = rand(BoundingBox())
        @layer begin
            translate(pos)
            rotate(rand() * 2π)
            placeimage(_readsvg_string(svgstring), O, centered = rand(Bool)) 
        end
    end
end
```

If you can think of a tidier UI - this isn't very pretty... :)

**Comment by guo-yong-zhi** [comment]
And `@png`? How to `readpng_string`? And does `Drawing` has any key to determine that what type of data its `bufferdata` contains?

**Comment by cormullion** [comment]
No idea! :) I've never heard of a PNG string... But this would work, presumably:

```julia
using Luxor

Drawing(100, 100, :png)
origin()    
juliacircles(10) 
pngdata = image_as_matrix()
finish()

@draw begin
    for i in 1:50
        pos = rand(BoundingBox())
        @layer begin
            translate(pos)
            rotate(rand() * 2π)
            placeimage(pngdata, O, centered = rand(Bool)) 
        end
    end
end
```

**Comment by hustf** [comment]
Regarding code docstrings, I notice 'alpha' is not well covered. I tend to use methods(fname) less and less, since more often than before, every method signature is included in docstrings.

I believe there's a conscious choice made here, to make a consistently helpful user guide than a type-oriented complete documentation for the REPL guy?

**Comment by cormullion** [comment]
Not sure what you mean... I try to update the manual and docstrings together, but it's never going to be perfect... It's difficult to maintain consistency over a long time and with lots of contributors (who often 'forget' to do the documentation updates😃). But perhaps this should be a separate issue (and PR)? Luxor.jl is old enough to need a face-lift in places.

**Comment by guo-yong-zhi** [comment]
I have integrated your function into PR https://github.com/JuliaGraphics/Luxor.jl/pull/136, but there are still 2 problems remain: svg alpha and png Drawing. Both of them are thorny.

**Comment by guo-yong-zhi** [comment]
I think I found something. That's it.
https://github.com/JuliaGraphics/Luxor.jl/blob/3cfae3e9df741f2f85b02a5fe652e64fee4fae26/src/drawings.jl#L414
```julia
m1 = Drawing(40,40, :svg)
origin()
background("white")
sethue("black")
background(0,1,1,0)
juliacircles(10) 
finish()
preview()

@draw begin
    for i in 1:50
        pos = rand(BoundingBox())
        @layer begin
            translate(pos)
            rotate(rand() * 2π)
            background(1,1,1,0)
            placeimage(m1, centered = rand(Bool))   # <-
        end
    end
end 100 100
```
->
![图片](https://user-images.githubusercontent.com/55872791/105361869-21802380-5c35-11eb-8384-d5807b05ab95.png)
but
```julia
m1 = Drawing(40,40, :svg)
origin()
#background("white") <- 
sethue("black")
background(0,1,1,0)
juliacircles(10) 
finish()
preview()

@draw begin
    for i in 1:50
        pos = rand(BoundingBox())
        @layer begin
            translate(pos)
            rotate(rand() * 2π)
            background(1,1,1,0)
            placeimage(m1, centered = rand(Bool))   # <-
        end
    end
end 100 100
```
->
![图片](https://user-images.githubusercontent.com/55872791/105362005-51c7c200-5c35-11eb-9454-134e137da801.png)

**Comment by guo-yong-zhi** [comment]
`CairoSVGSurface` 's background doesn't override, it's overlap. Maybe.

**Comment by guo-yong-zhi** [comment]
closed with https://github.com/JuliaGraphics/Luxor.jl/pull/138
