### ISSUE TITLE
Missing documentation of 'alpha' in src/images.jl

### ISSUE THREAD

**Issue by hustf** [JuliaGraphics/Luxor.jl#137]
Already mentioned in #134.

The documentation is generally very impressive, and even inspiring to read. It is on my to-do list both to learn to use Documenter.jl and proper formatting of docstrings. So I won't contribute with a PR just now, but if somebody is taking a brush over the documentation in the future, this might be easy to miss (well, I did) - and a useful feature.

From src/images.jl:64:
```
"""
    placeimage(img, xpos, ypos, a; centered=false)
Place a PNG image on the drawing at (`xpos`/`ypos`) with transparency `a`.
Use keyword `centered=true` to place the center of the image at the position.
"""
function placeimage(img::Cairo.CairoSurface, xpos, ypos, alpha; centered=false)

```

**Comment by cormullion** [comment]
I've edited it locally to this:

```julia
"""
    placeimage(img, pt::Point, alpha; centered=false)

Place a PNG image on the drawing at `pt` with transparency `alpha`.

Use keyword `centered=true` to place the center of the image at the position.
"""
placeimage(img::Cairo.CairoSurface, pt::Point, alpha; kwargs...) =
  placeimage(img::Cairo.CairoSurface, pt.x, pt.y, alpha; kwargs...)

```

Is this the change you were thinking of?

**Comment by hustf** [comment]
Thanks to Stale for the notice! 

The line  75:
`Place a PNG image on the drawing at `pt` with transparency `alpha`.`
can be copied to line 59.

But I'm not sure if this would be an improvement without also replacing 'a' in line 57:
`    placeimage(img, xpos, ypos, alpa; centered=false)`

...and in line 73:
`    placeimage(img, pos, alpha; centered=false)
`
This issue should perhaps die in shame. As far as I can see, the inline docs are already internally consistent. The function signatures generally drop type information and use (usually) more descriptive names instead. When skimming the inline documentation, this appeared as confusing to me, but that's just habit. Most sensible people have better things to do than reading curly brackets and double colons.
