### ISSUE TITLE
ffmpeg error creating animated gif in VSCode

### ISSUE THREAD

**Issue by rmsrosa** [JuliaGraphics/Luxor.jl#143]
I am getting an error that only happens in the REPL spawned by VSCode, not in the usual REPL. I am trying out some Luxor.jl code to create gif animations. This one, for instance:

```julia
# Adapted from [Cormullian's Slackmojiv's post](https://cormullion.github.io/pages/2019-06-23-slackmojif/)
using Luxor
function frame(scene, framenumber)
    nfn = rescale(framenumber, scene.framerange.start, scene.framerange.stop)
    rotate(π*sin(nfn * 2π))
    juliacircles(18)
end
size = 64
mymovie = Movie(size, size, "mymovie")
animate(mymovie, [Scene(mymovie, frame, 1:60)],
    creategif=true, pathname="juliafullrocker$(size)x$(size).gif")
```

In the REPL, there is no problem, and the animated gif is created:
```julia
julia> animate(mymovie, [Scene(mymovie, frame, 1:60)],
           creategif=true,
           pathname="juliafullrocker$(size)x$(size).gif")
┌ Info: Frames for animation "mymovie" are being stored in directory: 
└        /var/folders/yj/2q95f5rd57n7_6_q2jym158w0000gn/T/jl_VTM3dX
┌ Warning: Movie framerange is longer than scene frame range: 
│        1:250 > 60
└ @ Luxor ~/.julia/packages/Luxor/LqBTI/src/animate.jl:185
┌ Info: ... 60 frames saved in directory:
└        /var/folders/yj/2q95f5rd57n7_6_q2jym158w0000gn/T/jl_VTM3dX
[ Info: GIF is: juliafullrocker64x64.gif
Luxor.AnimatedGif("juliafullrocker64x64.gif")
```

But when I run it from inside vscode, I get the error

```julia
┌ Info: Frames for animation "mymovie" are being stored in directory: 
└        /var/folders/yj/2q95f5rd57n7_6_q2jym158w0000gn/T/jl_atDRrp
┌ Warning: Movie framerange is longer than scene frame range: 
│        1:250 > 60
└ @ Luxor ~/.julia/packages/Luxor/XSNgj/src/animate.jl:185
┌ Info: ... 60 frames saved in directory:
└        /var/folders/yj/2q95f5rd57n7_6_q2jym158w0000gn/T/jl_atDRrp
ERROR: LoadError: IOError: could not spawn `ffmpeg -loglevel panic -framerate 30 -f image2 -i /var/folders/yj/2q95f5rd57n7_6_q2jym158w0000gn/T/jl_atDRrp/%10d.png -filter_complex '[0:v] split [a][b]; [a] palettegen=stats_mode=full:reserve_transparent=on:transparency_color=FFFFFF [p]; [b][p] paletteuse=new=1:alpha_threshold=128' -y /var/folders/yj/2q95f5rd57n7_6_q2jym158w0000gn/T/jl_atDRrp/mymovie.gif`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at ./process.jl:99
 [2] #585 at ./process.jl:112 [inlined]
 [3] setup_stdios(::Base.var"#585#586"{Cmd}, ::Array{Any,1}) at ./process.jl:196
 [4] _spawn at ./process.jl:111 [inlined]
 [5] run(::Cmd; wait::Bool) at ./process.jl:439
 [6] run at ./process.jl:438 [inlined]
 [7] animate(::Movie, ::Array{Scene,1}; creategif::Bool, framerate::Int64, pathname::String, tempdirectory::String, usenewffmpeg::Bool) at /Users/rrosa/.julia/packages/Luxor/XSNgj/src/animate.jl:211
 [8] top-level scope at /Users/rrosa/Documents/git_repositories/julia/julia_random_stuff/src/luxor_animated_gif/src/julia_rocker.jl:16
in expression starting at /Users/rrosa/Documents/git_repositories/julia/julia_random_stuff/src/luxor_animated_gif/src/julia_rocker.jl:16
```

I created a separate environment just to test that. This is what I have:

```julia
(luxor_animated_gif) pkg> st
Status `~/Documents/git_repositories/julia/julia_random_stuff/src/luxor_animated_gif/Project.toml`
  [ae8d54c2] Luxor v2.9.0
```

and the system:

```julia
julia> versioninfo()
Julia Version 1.5.3
Commit 788b2c77c1 (2020-11-09 13:37 UTC)
Platform Info:
  OS: macOS (x86_64-apple-darwin18.7.0)
  CPU: Intel(R) Core(TM) m5-6Y54 CPU @ 1.10GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_NUM_THREADS = 2
```

Thank you for the great package, by the way!

**Comment by cormullion** [comment]
I can't reproduce this on my machine. ☹️ Even after I upgraded VSCode to the current version (and the Julia extension to 1.1.31) it still worked reliably, both from the editor and from the REPL, and both setting the `usenewffmpeg` flag in `animate()` to true and to false.

It might be some kind of weird timing bug, but I can't work out how to trigger it.

**Comment by rmsrosa** [comment]
Weird. And I forgot to say that I am using the latest  VSCode version 1.53.2 and the latest Julia extension v1.1.31. Here is the full VSCode info:
```
Version: 1.53.2
Commit: 622cb03f7e070a9670c94bae1a45d78d7181fbd4
Date: 2021-02-11T11:45:54.515Z (2 wks ago)
Electron: 11.2.1
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

**Comment by hustf** [comment]
In windows, I need to start vscode with elevated privileges to spawn some nodejs processes. And I have also seen some randomness with regards to the warning about number of frames. The latter is perhaps due to compiled functions and global variables? Perhaps the two messages have different causes?

**Comment by cormullion** [comment]
Thanks, @hustf - I hadn't thought of permissions problems, it's a possibility. Interfacing with  external processes like `ffmpeg` introduces complexity. ..

The only related issue I can find is this - https://github.com/JuliaPlots/Plots.jl/issues/3271 - same error message, but that's tied to a NixOS issue.

**Comment by rmsrosa** [comment]
Yeah, I have been trying things with the people in the Humans of Julia discord and it might indeed be something up with permissions. But @hustf , how do you "to start vscode with elevated privileges"? Like `sudo code .`?

**Comment by rmsrosa** [comment]
It is definitely a path problem, but not at all related to Luxor.jl! Sorry about that @cormullion !

But it is something about vscode/julia extension, either with my setup or in general. This is what I get in the vscode spawn REPL:

```julia
julia> run(`/usr/local/bin/ffmpeg`)
ffmpeg version N-98849-g026fea827d-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers

julia> run(`ffmpeg`)
ERROR: IOError: could not spawn `ffmpeg`: no such file or directory (ENOENT)
Stacktrace:
 [1] _spawn_primitive(::String, ::Cmd, ::Array{Any,1}) at ./process.jl:99
 [2] #585 at ./process.jl:112 [inlined]
 [3] setup_stdios(::Base.var"#585#586"{Cmd}, ::Array{Any,1}) at ./process.jl:196
 [4] _spawn at ./process.jl:111 [inlined]
 [5] run(::Cmd; wait::Bool) at ./process.jl:439
 [6] run(::Cmd) at ./process.jl:438
 [7] top-level scope at REPL[1]:1
```

@cormullion , I think we can close this issue. I will go back to the people at the Julia extension and see if they can help me. Thanks a lot!

**Comment by hustf** [comment]
@rmrosa, I don't know how privileges work in the Mac world. The 'admin' or 'elevated' trick is a Windows problem.

Glad to see you found the answer  elsewhere!

**Comment by rmsrosa** [comment]
I didn't find the answer yet, just a more appropriate question! rsrsrs

**Comment by rmsrosa** [comment]
Ok, I found the answer (at the same time with help in both Slack and Discord). It turned out I had `terminal.integrated.inheritEnv` unchecked in the julia extension of vscode. I am sure I didn't change that. Maybe it wasn't the default when I first installed it, but it should be the default now, since other people didn't run into the same problem.

Thanks both for your help!

**Comment by cormullion** [comment]
Good detective work! I don't remember setting that either - but there are so many VSCode settings... 🤷
