### ISSUE TITLE
Escaping width and height in @imagematrix

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaGraphics/Luxor.jl#144]
Hi! Thanks for a nice package :slightly_smiling_face: 

Could you add escaping of `width` and `height` in `@imagematrix` and `@imagematrix!` macros?
https://github.com/JuliaGraphics/Luxor.jl/blob/86b59a9460a8c0e41d7b9f67b27abfcab04f05f0/src/drawings.jl#L872-L881
This way I could pass variables there instead of just constants.

**Comment by cormullion** [comment]
Thanks!
