### ISSUE TITLE
Allow RecordingSurfaces?

### ISSUE THREAD

**Issue by hustf** [JuliaGraphics/Luxor.jl#147]
Hello, 
I have a lot of fun with Luxor and Julia in VSCode on Windows, but the existing 'preview()' doesn't quite work as I would hope. However, by mutating Drawing, we can still inspect drawings while making them. I think recording surfaces can work well with ad-hoc user macros.

I believe one should avoid adding much more functionality to Luxor or changing the original use case too much. The below code is an ugly hack, though, which could be avoided if the Drawing constructor was a little more lenient. Also, I did not find a good way to indicate that the current drawing surface is recording. I would like to make a minimal PR, but any pre-input would be appreciated. Is it OK to add stuff without having thought-through documentation for it?

P.S. Pictures are not intended for hypnosis, I promise.

Snap1.png
![snap1](https://user-images.githubusercontent.com/13949620/111033870-84ab5c80-8413-11eb-9de3-142eafb2e563.png)
Snap2.png
![snap2](https://user-images.githubusercontent.com/13949620/111033871-84ab5c80-8413-11eb-9a0c-7f83e0ce7ecf.png)
Snap3.png
![snap3](https://user-images.githubusercontent.com/13949620/111033868-837a2f80-8413-11eb-804b-f5036394672d.png)

```julia
using Luxor
import Luxor:       CairoContext, CairoRecordingSurface, set_source, CURRENTDRAWING
import Luxor.Cairo: flush

"""
    make_recording_surface_drawing()
    --> Luxor.Drawing

This makes, then mutates a Luxor drawing to allow 
a special type of Cairo surface. 
"""
function make_recording_surface_drawing()
    d = Drawing(640, 480, :svg)
    origin()
    background("yellow")
    s1 = CairoRecordingSurface()
    d.surface = s1
    d.cr = CairoContext(s1)
    d
end

"""
    snapshot_of_recording_surface(fnam)

Take a snapshot and save to 'fnam' name and suffix. 
One could continue drawing, or do the other things.

Internally, this stores the recording surface, then restores it.
"""
function snapshot_of_recording_surface(fnam)
    drec = currentdrawing()
    recmat = getmatrix()
    # Check that it's a recording surface, how? @assert typeof(drec.surface)
    flush(drec.surface)
    d = Drawing(drec.width, drec.height, fnam)
    d.width = drec.width
    d.height = drec.height
    d.redvalue = drec.redvalue
    d.greenvalue = drec.greenvalue
    d.bluevalue = drec.bluevalue
    d.alpha = drec.alpha
    setmatrix(recmat)
    #set_source(d.cr, drec.surface, 0, 0)
    set_source(d.cr, drec.surface, drec.width / 2, drec.height / 2)
    paint()
    finish()
    CURRENTDRAWING[1] = drec
end

function drawcentered()
    setline(8)
    Δα = mod(time() * 10, 6.3)
    for r = 0:20:500
        α = r / 100  + Δα
        circle(O + sqrt(r ) .* (cos(α), sin(α)), r, :stroke)
        settext("<span font = '16' foreground = 'darkblue' > $(string(r)) </span>", 
            O + (0, 8 -r ); markup = true)
    end
end
make_recording_surface_drawing()

sethue("gold4")
drawcentered()
snapshot_of_recording_surface("snap1.png")

sethue("gold3")
drawcentered()
snapshot_of_recording_surface("snap2.png")

sethue("gold1")
drawcentered()
snapshot_of_recording_surface("snap3.png")
```

**Comment by cormullion** [comment]
Cool! I'm happy to add any new stuff that people contribute, as long as all my existing Luxor code keeps working (and is backwards-compatible back to Julia v1.3). I'm happy to add/update docs later once any issues are sorted.

The function names are a bit long - any movement possible on those?

**Comment by hustf** [comment]
I didn't even get the tea hot!
Actually, I don't think those functions should be added as they are at all. I'm thinking about primarily extending the existing Drawing interface. Now, there is a field called Drawing.surfacetype. But this is ambiguous. To me, it just seems like it described the file type.

A Recording Surface can be any type I think. As far as I know, .svg is the format which can handle everything, but we could set the surface type field to e.g. :recsurf? However, is that field actually used anywhere? I don't know yet.

**Comment by hustf** [comment]
Also: Instead of complaining that there's no 'Current drawing', we could simply make a recording surface, and leave any complaints until the used wants to 'finish( without supplying a filename).  But there's a chance that has more unintended consequences? I have never used some of the file formats.

**Comment by cormullion** [comment]
Like human evolution, things in Luxor may have evolved in possibly peculiar ways, but it was probably to avoid breaking stuff. If we were to start all over again, it might indeed be different... Julia has also evolved a bit since 2014. 😄

If you can extend Drawing without breaking anything, go for it!

**Comment by hustf** [comment]
The large rewrites are sometimes not so fun after all. A small PR is coming your way, but likely in a week or so.

**Comment by hustf** [comment]
[Recording surfaces](https://www.cairographics.org/manual/cairo-Recording-Surfaces.html) allow for more flexibility, but Cairo.jl does not fully implement everything yet. But this is already useable, though we should at least add the ability of snapshotting any rectangle on screen.

**Comment by hustf** [comment]
I considered, but didn't, include the following in #148. It's a small script for exposing the script from recording surfaces. Tinkering with internals scripts could be useful, ref. #123. I also noticed @lobingera has [outlined a package](https://github.com/lobingera/CairoScript.jl/tree/master/src) for modifying scripts.

```
using Luxor, Test
import Luxor.Cairo

function readrecord()
    rd = currentdrawing()
    isbits(rd) && return false  # currentdrawing provided 'info'
    rs = Luxor.current_surface()
    buf = IOBuffer()
    sc = Cairo.CairoScript(buf)
    Cairo.script_from_recording_surface(sc, rs)
    String(take!(buf))
end
Drawing(640, 480, :rec)
sethue("red")
box(O, O + (300, 200), :stroke)
box(O, O + (200, 100), :stroke)
snapshot()
println(readrecord())
```

**Comment by cormullion** [comment]
Now merged into `master`, awaiting documentation... 😄
