### ISSUE TITLE
Quick question about polysample omitting the first point in a curve

### ISSUE THREAD

**Issue by JeffreyPalmer** [JuliaGraphics/Luxor.jl#168]
Hi! I was wondering if you could clarify something for me.

I use `polysample` to create many sample points for a curve, but I've noticed that it omits the start point. (I'm generally working with open polygons, so perhaps that's the issue?)

If you could help me understand why the start point is omitted that would be helpful. At the moment I have a wrapper function that simply adds the first point back in, but that seems like it shouldn't be necessary.

Thanks!

**Comment by cormullion** [comment]
Yes, I think that's the way to go, if you want to keep a particular point. My view of "sampling" was that it didn't have to include any points from the original - which could easily be added if you wanted them. I suppose my mental model is:

<img width="554" alt="Screenshot 2021-07-31 at 10 15 28" src="https://user-images.githubusercontent.com/52289/127735280-a250187b-b9b2-494c-bb85-3c27a77e342d.png">

Perhaps a keyword option for keeping the first point might be an idea...

**Comment by JeffreyPalmer** [comment]
This makes total sense to me for closed polygons. For my open polygon use cases it feels like it would be more natural to retain the endpoints and interpolate the remaining n-2 points between them.

Maybe I need/should create a different function that has those semantics? I don't want to try to force something to happen if I have misunderstood the intent of `polysample`. I'm happy to use one of my own devising - I just want to be sure I'm not missing something.

Thanks for your help!

**Comment by cormullion** [comment]
New features/functions are very welcome!

This API isn't trying to match an existing specification or copy another API - I've just been adding functions as and when I need them, for my own purposes. I try to make them general but obviously it's easy to  miss some obvious things that I hadn't thought of. With your wider experience of other APIs you're in a good position to see the holes!

Julia's multi-method functions and fast keywords make it easy to use the same function name for different tasks, but in this case I'm not sure whether `polysample()` could stretch to  accommodate much in the way of additional functionality. Perhaps a `polyinterpolate()` function would work? 

One problem with the polygon-functions is to avoid duplicating the start and end points - there's often no check for duplicated points, and that will provoke errors down the line. Handling both open and closed interpretations of polygons has been a bit of a pain, as you can see... :)

**Comment by JeffreyPalmer** [comment]
Thanks for the additional detail. I'll consider adding a `polyinterpolate` function after I pin down exactly what I'm looking for. I'm going to close this in the meantime. Thanks!
