### ISSUE TITLE
`getindex` on Point allocates

### ISSUE THREAD

**Issue by tomerarnon** [JuliaGraphics/Luxor.jl#169]
Due to this line in `point.jl`:
https://github.com/JuliaGraphics/Luxor.jl/blob/c5af012e8e34803a6f4fb3386b63c9ea5473bb01/src/point.jl#L45

indexing a `Point` allocates a vector first. Replacing this with a tuple instead eliminates the allocation. The probably has implications in many places `Point`s are used.

From a skim of nearby code, I noticed same thing could be happening in `dotproduct` with `[:x, :y]`, although I haven't run in to that in my own uses yet. Actually, is there any reason not to simply write that function as `p1.x*p2.x + p1.y*p2.y`?

**Comment by cormullion** [comment]
Hi! I've never worried about speed or performance, so there are probably plenty of places where the basic algorithm was my main or only concern... So there's plenty of scope for performance enhancements, I'm sure, just waiting for someone knowledgable to contribute their insights!

**Comment by tomerarnon** [comment]
Fair enough! I encountered it when looking into performance and figured I'd bring it up.

**Comment by cormullion** [comment]
I'll change it to `Base.getindex(p::Point, i) = (p.x, p.y)[i]` and see what happens - so far I can't see anything getting worse.
