### ISSUE TITLE
Luxor in notebook on Julia 0.6 = world error

### ISSUE THREAD

**Issue by KristofferC** [JuliaGraphics/Luxor.jl#17]
Tried to use Luxor but something seems a bit odd:

![image](https://cloud.githubusercontent.com/assets/1282691/26038028/c00fe3e4-38ff-11e7-93aa-617fcdaa1410.png)

Not sure if the problem is here but thought I would post an issue anyway...

**Comment by cormullion** [comment]
Thanks, Kris, looks strangely familiar... :). I wonder whether this is just general v0.6 flakiness, or something else. I've been struggling to get some other basic packages working too - I've been getting QuartzIO errors, for example. But this one seems OK:

![screen shot 2017-05-14 at 23 08 16](https://cloud.githubusercontent.com/assets/52289/26038190/5fe0db0e-38fa-11e7-88f9-03f467c24aa2.png)

(Note that you probably want to choose a non-white color for text.)

**Comment by KristofferC** [comment]
Okay, maybe it is something strange with my setup then. Anyway, it seems that the problem is not here. Sorry for noise :)

**Comment by cormullion** [comment]
No problem - nice that someone's trying to use it.😀

**Comment by cormullion** [comment]
This hasn't gone away like I thought it might. Julia v0.6 should be stable by now. So it might be fixable here.

**Comment by ggggggggg** [comment]
I tried using Luxor in Juliabox with a 0.6 kernel. At first I had problems (like infinite freeze), but then I ran `Pkg.add("ImageMagick")` and the following works: 
```
using Luxor
@png begin
        fontsize(50)
        circle(O, 150, :stroke)
        text("hello world", halign=:center, valign=:middle)
     end
```

But if I use `@svg` instead of `@png` the text is unreadable.

Should `ImageMagick` be in `REQUIRE`?

**Comment by cormullion** [comment]
@ggggggggg I've not tested Luxor on JuliaBox (my experiences with JBox haven't been encouraging) but I'll have another look tomorrow.

**Comment by cormullion** [comment]
I finally managed to get JuliaBox working again, but to me it's the SVG that works OK, and the PNG format that might need some help from ImageMagick on Linux. (ImageMagick isn't needed on macOS.)

![screen shot 2017-09-13 at 08 07 24](https://user-images.githubusercontent.com/52289/30365237-ffdabb8e-985e-11e7-9510-a3b2fc06a5a0.png)

I'll find out how to add conditional dependencies (require ImageMagick only on Linux...).

**Comment by cormullion** [comment]
More about world age errors [on this Discourse post](https://discourse.julialang.org/t/running-in-world-age-x-while-current-world-is-y-errors/5871). I've no idea how to stop the error appearing though...

**Comment by cormullion** [comment]
https://github.com/JuliaLang/IJulia.jl/issues/609
