### ISSUE TITLE
Display output in Juno Plot pane

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Luxor.jl#18]
By loading this code:

```
using Juno, Hiccup

Media.media(Drawing, Media.Plot)

function Media.render(pane::Juno.PlotPane, img::Drawing)
    Media.render(pane, Hiccup.div(Hiccup.img(src=img.filename)))
end
```

it's sort of possible to display output in a Juno Plot pane:

![screen shot 2017-05-15 at 11 08 34](https://cloud.githubusercontent.com/assets/52289/26065585/5cc72382-398c-11e7-8ad0-8f330ac7920f.png)

However, this doesn't update when the file changes, so it's not yet working satisfactorily.

**Comment by cormullion** [comment]
The code can be improved (https://github.com/JunoLab/Juno.jl/issues/58) by adding a browser-fooling URL:

```
using Luxor
using Juno, Hiccup
Juno.media(MyType, Media.Plot)
Juno.media(MyType, Media.Graphical)

function Juno.render(pane::Juno.PlotPane, img::Drawing)
    Juno.render(pane, Hiccup.div(Hiccup.img(src=img.filename*"?$(time())")))
end

cd("/tmp")
Drawing("A6", "/tmp/t17.png")
background("grey20")
origin()
randomhue()
R = rand(30:63)
epitrochoid(R, rand(12:41), rand(5:137), :stroke)
fontsize(70)
sethue("white")
text(string(R))
finish()
display(currentdrawing)
```

![screen shot 2017-05-16 at 10 33 56](https://cloud.githubusercontent.com/assets/52289/26099626/375e0876-3a23-11e7-9eba-376ef9c80ae4.png)

This might be added to the Luxor package one day, perhaps when there are conditional dependencies (i.e. "load this code only if Juno is available".

**Comment by pfitzseb** [comment]
Okay, so our design idea here was that you'll only need to depend on Juno, which is super small and lightweight (because it and all it's dependecies are pure Julia) and can then call `Juno.isactive()` as a guard around your `render` definitions. 
This approach shouldn't add much overhead, but still work around the conditional requirements issue. Still, it's of course up to you if you want to support native Juno plotting right now :)

**Comment by cormullion** [comment]
Oh, it's easier than I thought... ! I'll have a crack at it today or tomorrow!

**Comment by pfitzseb** [comment]
Great :)
Btw, you don't even need to save the svg to a file -- dumping the svg contents into the plot pane directly works too.

**Comment by cormullion** [comment]
Added code to support Juno in [this](https://github.com/JuliaGraphics/Luxor.jl/commit/6682d0c8fe344105061ff326abf3c8c449046809) commit, see how it works...
