### ISSUE TITLE
Functions line, rline does not works?

### ISSUE THREAD

**Issue by achjaj** [JuliaGraphics/Luxor.jl#182]
When I try to draw a line using eighter `line(pt, pt)`, `line(pt)` or `rline(pt)`, then nothing is drawn in the final image.
Here is what I tried:
```
Drawing(500, 500, "test.png")
origin()
line(O, Point(100, 100))
line(Point(150, 150))
rline(Point(50, 200))
finish()
preview()
```
When I call `preview()` function only a blank image is shown, with the same result for an SVG drawing. The above code is executed without any errors.
I can draw for example a circle or I can use `rule` function to draw a line. 

I am using Luxor v2.17.0 on Julia 1.6.3

**Comment by cormullion** [comment]
You should apply an action to the path that you've just constructed. `strokepath()` is a good choice.

**Comment by achjaj** [comment]
Thank you. I thought that the drawing is done in the `finish()` function. Actually, the `strokepath()` action in combination with `line(pt)` function didn't worked, but `line(pt, pt, :stroke)` did.

**Comment by cormullion** [comment]
Glad you got it working. This works:

<img width="915" alt="Screenshot 2021-11-19 at 14 16 13" src="https://user-images.githubusercontent.com/52289/142637036-6739d70a-53e1-4897-8575-fb8dc04e550b.png">

**Comment by achjaj** [comment]
I see. So, if I understand it correctly, I have to start with `line(pt, pt)` otherwise the `line(pt)` function doesn't know where to start, am I right?

**Comment by cormullion** [comment]
Cairo has the concept of a "current point", which is not set until you do a `move` or `line` (I think), More [here](https://cairographics.org/manual/cairo-Paths.html#cairo-line-to).

So

```
Drawing(500, 500, "test.png")
background("white")
origin()
@show hascurrentpoint()
line(Point(100, -150))
...
```
shows `false`.  

It's usual to start with a `move` because you typically don't want to draw lines from a point in the previous path.

**Comment by achjaj** [comment]
Thank you, you were very helpful.
