### ISSUE TITLE
`preview()` in VS Code on Windows

### ISSUE THREAD

**Issue by zmoon** [JuliaGraphics/Luxor.jl#183]
Creating an SVG, when I finish and preview it, it opens in both the plots pane of the editor and in default web browser. Is there a way to disable the latter in this context?

**Comment by cormullion** [comment]
Hi! I don't know, but it might be some bad coding on my part, because when VS-Code for Julia was released I didn't add proper code to handle it, like it handles Atom and Jupyter. Now that Atom is becoming deprecated, perhaps I should finally write for VS-Code rather than Atom (but I still use Atom... 😃).

**Comment by zmoon** [comment]
It seems like VSCodeServer has similar ways to check like Juno. Maybe checking `VSCodeServer.PLOT_PANE_ENABLED`? It would maybe be nice to be able to do these checks without making VSCodeServer and Juno dependencies of Luxor.

**Comment by hustf** [comment]
An obnoxious question; sorry: Could this be just how VSCode treats svg files? Since it is a text format, the expected behaviour for the editor is to display it as text. If so, one option is to install an svg plugin in VSCode. Another is to change the workflow to

```
Drawing(640, 480, :rec)
....
snapshot(fname = "temp.svg")
```
Simply calling `snapshot()` would display a preview.

**Comment by zmoon** [comment]
The automatic display (as an image, not the SVG source) with the Julia VS Code plot pane I like, and that is something that VSCodeServer (part of Julia's VS Code extension) is doing automatically. What I find slightly annoying is it also getting opened in the web browser at the same time. So it seems like adding a check for VS Code to the current logic would work fine. But I don't know the Julian way to do that without having Juno and VSCodeServer as explicit dependencies.

**Comment by hustf** [comment]
How does one change Window's default behaviour of opening Edge when it gets an svg? That is what happens when running from the REPL too. It does not happen when running from the terminal inside of VSCode, at least with my setup.

The 'leave it to the operating system' behaviour is problematic with bitmap files, too. The current Windows  has a preview function which interferes randomly with modifying the file.

There's no one correct way of treating output, I guess?

**Comment by zmoon** [comment]
> I've asked Seb on Zulip (https://julialang.zulipchat.com/#narrow/stream/234266-vscode/topic/Avoiding.20double.20display/near/263703734) if my proposed solution will work properly

Cool. I think it might be better to check `VSCodeServer.PLOT_PANE_ENABLED[]` though, since the user can disable the plot plane, and then Luxor could fall back to calling the OS / opening browser for the preview.

**Comment by cormullion** [comment]
Would that require adding a dependency on VSCode though? I want to remove the Juno dependency one day, and don't want to add another...

**Comment by zmoon** [comment]
@cormullion I believe you could do it this way that I suggested above, which doesn't require `using VSCodeServer`:
```
isdefined(Main, :VSCodeServer) && VSCodeServer.PLOT_PANE_ENABLED[]
```
and possibly similarly for Juno, though I didn't try it:
```
isdefined(Main, :Juno) && Juno.isactive()
```

**Comment by cormullion** [comment]
I tried this:

```julia
if (get(io, :jupyter, false) || Juno.isactive() || (isdefined(Main, :VSCodeServer) && VSCodeServer.PLOT_PANE_ENABLED[]) &&
            (d.surfacetype == :svg || d.surfacetype == :png))
    return d.filename
end
```

But that didn't work in VSCode:

```julia
ERROR: UndefVarError: VSCodeServer not defined
Stacktrace:
  [1] show(io::IOContext{Base.TTY}, #unused#::MIME{Symbol("text/plain")}, d::Luxor.Drawing)
    @ Luxor ~/.julia/dev/Luxor/src/drawings.jl:134
  [2] (::REPL.var"#43#44"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::Any)
    @ REPL /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/REPL.jl:264
  [3] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/REPL.jl:508
  [4] display(d::REPL.REPLDisplay, mime::MIME{Symbol("text/plain")}, x::Any)
    @ REPL /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/REPL.jl:257
  [5] display(d::REPL.REPLDisplay, x::Any)
    @ REPL /Applications/Julia-1.7.app/Contents/Resources/julia/share/julia/stdlib/v1.7/REPL/src/REPL.jl:269
  [6] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:328
  [7] #15
    @ ~/.julia/packages/Media/ItEPc/src/compat.jl:28 [inlined]
  [8] hookless(f::Media.var"#15#16"{Luxor.Drawing})
    @ Media ~/.julia/packages/Media/ItEPc/src/compat.jl:14
  [9] render
    @ ~/.julia/packages/Media/ItEPc/src/compat.jl:27 [inlined]
 [10] render(x::Luxor.Drawing)
    @ Media ~/.julia/packages/Media/ItEPc/src/system.jl:160
 [11] display(#unused#::Media.DisplayHook, x::Luxor.Drawing)
    @ Media ~/.julia/packages/Media/ItEPc/src/compat.jl:9
 [12] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:328
 [13] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
 [14] invokelatest
    @ ./essentials.jl:714 [inlined]
 [15] (::VSCodeServer.var"#60#64"{Bool, Bool, Module, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-insider-1.5.6/scripts/packages/VSCodeServer/src/eval.jl:203
 [16] withpath(f::VSCodeServer.var"#60#64"{Bool, Bool, Module, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams}, path::String)
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-insider-1.5.6/scripts/packages/VSCodeServer/src/repl.jl:185
 [17] (::VSCodeServer.var"#59#63"{Bool, Bool, Bool, Module, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-insider-1.5.6/scripts/packages/VSCodeServer/src/eval.jl:180
 [18] hideprompt(f::VSCodeServer.var"#59#63"{Bool, Bool, Bool, Module, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-insider-1.5.6/scripts/packages/VSCodeServer/src/repl.jl:36
 [19] (::VSCodeServer.var"#58#62"{Bool, Bool, Bool, Module, Int64, Int64, String, VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-insider-1.5.6/scripts/packages/VSCodeServer/src/eval.jl:151
 [20] with_logstate(f::Function, logstate::Any)
    @ Base.CoreLogging ./logging.jl:511
 [21] with_logger
    @ ./logging.jl:623 [inlined]
 [22] (::VSCodeServer.var"#57#61"{VSCodeServer.ReplRunCodeRequestParams})()
    @ VSCodeServer ~/.vscode/extensions/julialang.language-julia-insider-1.5.6/scripts/packages/VSCodeServer/src/eval.jl:228
 [23] #invokelatest#2
    @ ./essentials.jl:716 [inlined]
 [24] invokelatest(::Any)
    @ Base ./essentials.jl:714
 [25] macro expansion
    @ ~/.vscode/extensions/julialang.language-julia-insider-1.5.6/scripts/packages/VSCodeServer/src/eval.jl:34 [inlined]
 [26] (::VSCodeServer.var"#55#56")()
    @ VSCodeServer ./task.jl:423
```

If you can get something working reliably, you could make a PR.

**Comment by zmoon** [comment]
@cormullion weird, I tried copying yours in and it worked for me (using "Julia: execute active File in REPL"). And I have the same Julia version and Julia VS Code extension version, but on Windows. I'll try to do some more experimentation. Also your traceback is kind of confusing to me since it says `VSCodeServer` not defined but then there are lots of references to parts of it.

**Comment by cormullion** [comment]
Yes, it’s confusing. 

On master at the moment is my previous attempt, which might be better than the release version. Unfortunately the RSVG issue (broken Rust tool chain 🤷😱🤔) prevents tests passing on Windows at the moment.

**Comment by oheil** [comment]
I'm not able to reproduce this. It just shows the svg in the pane of VisualStudio, no extra in a browser.
Perhaps the problem somehow disappeared? Issue can be closed?
I checked only on Windows.

**Comment by cormullion** [comment]
Perhaps I managed to fix it while attempting to fix it... Stranger things have happened. Can always be re-opened...
