### ISSUE TITLE
`arc` and `carc` argument list varies 

### ISSUE THREAD

**Issue by hustf** [JuliaGraphics/Luxor.jl#184]
Quite minor, quite unexpected bug popped up today. Perhaps a good first PR?

To reproduce:
```
(r, β_sta, β_cutoff) = (43.5, -1.57, -4.99)
carc(0, 0, r,  β_sta, β_cutoff, :stroke)
# Workaround:
arc(0, 0, r, β_sta, β_cutoff, action = :stroke)
# This does not work:
arc(0, 0, r, β_sta, β_cutoff, :stroke)
```

```
ERROR: MethodError: no method matching arc(::Int64, ::Int64, ::Float64, ::Float64, ::Float64, ::Symbol)
Closest candidates are:
  arc(::Any, ::Any, ::Any, ::Any, ::Any; action) at C:\Users\f\.julia\packages\Luxor\rOUAt\src\curves.jl:167
  arc(::Point, ::Any, ::Any, ::Any; action) at C:\Users\f\.julia\packages\Luxor\rOUAt\src\curves.jl:182
  arc(::Point, ::Any, ::Any, ::Any, ::Symbol) at C:\Users\f\.julia\packages\Luxor\rOUAt\src\curves.jl:185
Stacktrace:
 [1] top-level scope
   @ REPL[13]:1
```
Edit: The line '#This does not work' is corrected. NOW it is not working...

**Comment by cormullion** [comment]
Thanks. I wonder if this is a bug introduced in the current release after I tried to “fix” https://github.com/JuliaGraphics/Luxor.jl/issues/174. When I’m at a computer I’ll investigate previous releases.

**Comment by cormullion** [comment]
Yes, I think that's a regression:

```julia
arc(0, 0, r, β_sta, β_cutoff, :stroke)
```

used to work in Luxor 2.15, but after I added all the `action=:stroke` methods the old `arc(x, y, ...` method is too ambiguous to resolve and needs another method to handle it. (But `arc(Point, ... action=:stroke` works OK.)

I'm thinking about taking all the old `(x, y...` methods away, keeping just the `(Point, ...` versions, so that you'd do `arc(Point(x, y), ...` instead of `arc(x, y, ... ` but that might be a breaking change for version 3.0... :)

**Comment by hustf** [comment]
I don't see the point in public (x, y..) methods either, but ´x´ is clearer to read than pt[1]. Perhaps keeping all these methods might cause fewer bugs during the transition - just head them up underscore: e.g. `_arc(x,y...`

We have these largely unnecessary `action` arguments, too. How about trying something like this out with the arc function?

```
@deprecate( arc(pt, r, β_sta, β_cutoff, action::Symbol),     
                     arc(pt::Point, r, β_sta, β_cutoff; action = replace), 
                     true)
```

I haven't tested the syntax, but the last argument means that the deprecation warnings won't be shy.
If this works as intended, we could have an effective mass exodus of ::Symbol as the last argument in all of this package? Personally, I would hope for `action = :stroke` as the default everywhere.

Then, in v3.0, simply delete all of the @deprecate lines?

**Comment by cormullion** [comment]
Yes, these are logical changes to make, of course. But I always wonder whether disruption is worth the improvement - eg for Julia 2.0 I hope we don't see too many changes that are like "this is a bit untidy, let's remove it/make it more consistent". 😃

**Comment by hustf** [comment]
Long term vs short term I guess. In the very long run, there will be other packages like this, perhaps when Cairo is replaced. This is working very well for me now, but font sizing not working at the moment is not so nice.
