### ISSUE TITLE
Question - Getting raw SVG and saving drawing

### ISSUE THREAD

**Issue by davibarreira** [JuliaGraphics/Luxor.jl#185]
Suppose the following example:
```
d = Drawing(500,500,:svg)
setopacity(0.85)
steps = 20
gap   = 2
for (n, θ) in enumerate(range(0, step=2π/steps, length=steps))
    sethue([Luxor.julia_green,
        Luxor.julia_red,
        Luxor.julia_purple,
        Luxor.julia_blue][mod1(n, 4)])
    sector(Point(0, 0), 50, 250 + 2n, θ, θ + 2π/steps - deg2rad(gap), :fill)
end
finish()
```
Whenever I call `d` in the notebook, the svg image is displayed, which is great. Now, I wish to obtain the raw SVG and also save this drawing as an SVG. Is there an easy/clean way of doing it? I've been reading the documentation, but the only way I've seen to obtain the raw svg would be with `svgtring`, which only works in the current drawing. The only solution I found was to place the image into another svg, and use something like:
```julia
function savesvg(d::Drawing, file="myfig.svg")
    fig = Drawing(d.width,d.height, file)
        placeimage(d)
    finish()
end

function rawsvg(d::Drawing)
    fig = Drawing(d.width,d.height,:svg)
        placeimage(d)
    finish()
    return svgstring()
end
```
This solution is fine, but then I'm creating another svg drawing, which seems unnecessary.

**Comment by cormullion** [comment]
Hi Davi! Thanks for trying Luxor. There are some peculiarities with the display/save system with all the permutations of file format and environment, I admit, and I can't say I really understand everything that goes on. :) 

Perhaps, if you want both the drawing and the source, you could use

```julia
using Luxor

d = Drawing(600, 600, :svg)
origin()
juliacircles(170)
finish()
svgsource = String(copy(Luxor.current_bufferdata()))
d 
```

where `d` displays the drawing, and `svgsource` contains the SVG. Is this what you had in mind?

**Comment by cormullion** [comment]
Cool! Thebes.jl is a bit of a toy, really, so adjust your expectations 😂

**Comment by davibarreira** [comment]
I have high expectations though :grin:, cause I have ambitious plans involving Luxor and Thebes :dancers:
