### ISSUE TITLE
`valign=:bottom` is equal to `valign=:baseline`

### ISSUE THREAD

**Issue by davibarreira** [JuliaGraphics/Luxor.jl#188]
I don't know if this is the expected behavior, but the `valign=:bottom` is equal to `valign=:baseline` when placing a text.
```julia
d = Drawing(300,300,:svg)
origin()
text("Baseline", valign=:baseline)
text("Bottom", valign=:bottom)
finish()
d
```
I thought the "Bottom" text should be placed above the "Baseline".

**Comment by cormullion** [comment]
This is what I see (MacOS) - are you running on a different platform? Try some different fonts too, perhaps?

<img width="1096" alt="Screenshot 2021-12-23 at 20 42 56" src="https://user-images.githubusercontent.com/52289/147290159-e03e6084-b2f9-4e88-baf7-a27b7f8a416f.png">

**Comment by davibarreira** [comment]
Oh, I see. Now that you mention, I can see a slight difference between `:baseline` and `:bottom`. Thanks! Sorry for opening the issue.
