### ISSUE TITLE
exact working of fillpath() not clear 

### ISSUE THREAD

**Issue by ArbitRandomUser** [JuliaGraphics/Luxor.jl#194]
```julia
Drawing(500,500,"test3.png");
origin()
background("white")
sethue("black")
s = :path
l=20
line(O,Point((l,0.0)),s)
line(Point((l,0.0)),Point(l,l),s)
line(Point(l,l),Point(0,l),s)
line(Point(0,l),O,s)
strokepreserve()
sethue("black")
setopacity(1.0)
fillpath()
finish()
preview()
```

what i expected was a filled box of size 20
but what i seem to get is 

![test3](https://user-images.githubusercontent.com/58146965/150599292-e6f0f5ba-8ded-4a08-91f9-4adc44118de7.png)

why isn't `fillpath` filling inside the square that i have drawn with 4 lines ?

**Comment by cormullion** [comment]
Hi! You can get an insight into what's happening by zooming in and noticing how the four lines you've drawn aren't joined together or mitred - so they're four separate things, not a single thing. Then, each one gets filled, but it's impossible to see a filled straight line. (But I think Cairo does try; if you look at the SVG output, it looks like the line segments are each filled.)

It's easier to add points one by one, to build up paths, than to add lots of separate line segments.

**Comment by ArbitRandomUser** [comment]
oh cool ; got it ! thanks
