### ISSUE TITLE
Is there a way to "id" the SVG produced with Luxor?

### ISSUE THREAD

**Issue by davibarreira** [JuliaGraphics/Luxor.jl#197]
In packages such as D3, we manipulate the current SVG by placing id's or tags in the generated SVG. I was wondering if something similar could be done in Luxor. This perhaps could help improve future interactive applications, as one could just slightly modify an SVG instead of rewriting the whole thing.

**Comment by davibarreira** [comment]
I mean, suppose I do a for loop placing circles. It would be nice if I could add an id to each circle. So if one of them changes, I just have to redraw that element. Of course, I know that the redraw would not be via Luxor, since it's not a tool to manipulate SVG.

**Comment by cormullion** [comment]
Hi! I don't think Cairo has anything that does that:

https://cairographics.org/manual/cairo-SVG-Surfaces.html

Looking at SVG output doesn't look promising:

```julia
@drawsvg begin
    background("black")
    
    circle(O, 10, :fill)
    box(O, 10, 100, :fill)
    
end

@show svgstring()

svgstring() = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n
<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" width=\"600pt\" height=\"600pt\" viewBox=\"0 0 600 600\" version=\"1.1\">\n
<g id=\"surface20426\">\n
<rect x=\"0\" y=\"0\" width=\"600\" height=\"600\" style=\"fill:rgb(0%,0%,0%);fill-opacity:1;stroke:none;\"/>\n
<path style=\" stroke:none;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;\" d=\"M 310 300 C 310 305.523438 305.523438 310 300 310 C 294.476562 310 290 305.523438 290 300 C 290 294.476562 294.476562 290 300 290 C 305.523438 290 310 294.476562 310 300 \"/>\n
<path style=\" stroke:none;fill-rule:nonzero;fill:rgb(0%,0%,0%);fill-opacity:1;\" d=\"M 295 350 L 295 250 L 305 250 L 305 350 Z M 295 350 \"/>\n
</g>\n
</svg>\n
"
```

So you'd probably have to build up all the graphics as data first, then output it all later as paths. Not really what Cairo/Luxor are designed for but possibly doable. 😄

**Comment by davibarreira** [comment]
Yeah, I thought so. Well, all good, it was just an extra in case it was easily doable :D

**Comment by hustf** [comment]
Hi, davidbarreira. I believe I asked for something similar in an earlier issue. This is hard, but modifying an svg file in other ways is easy. 

Here is a little snippet for reading from svg files.  It's not directly useful, but easily adaptible to the structure of your generated svg / xml code,  For adding attributes like 'id', see the documentation for EzXML or for svg files.

```
import EzXML
using EzXML: readxml, namespaces
"""
read_svg_element(svgfile, pathid)
 -> ExXML element
The path ID can be set in Inkscape -> select bezier path -> ctrl+shift+o, right hand side menu,
or in text file
"""
function read_svg_element(svgfile, pathid)
    # the xml parser is a separate binary, and may sometimes 'crash' silently. Close this process if that occurs
    if !isabspath(svgfile)
        svgfile = joinpath(@__DIR__, svgfile)
    end 
    xm = readxml(joinpath( "input", svgfile))
    nsdic =  Dict(map(namespaces(xm.root)) do (ke, va)
        if ke == ""
            "x", va
        else
            ke, va
        end
    end)
    xpath = "x:g/x:path[@id='$pathid']"
    elems = EzXML.findall(xpath, EzXML.root(xm), nsdic)
    @assert length(elems) == 1 "Could not identify $pathid"
    first(elems)
end
```

**Comment by davibarreira** [comment]
Thanks @hustf !
