### ISSUE TITLE
Add `MathTeXEngine` to dependencies

### ISSUE THREAD

**Issue by mossr** [JuliaGraphics/Luxor.jl#199]
Hey @cormullion—I get the standard "dependency" warning when using Luxor:
```julia
julia> using Luxor
┌ Warning: Package Luxor does not have MathTeXEngine in its dependencies:
│ - If you have Luxor checked out for development and have
│   added MathTeXEngine as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Luxor
└ Loading MathTeXEngine into Luxor from project dependency, future warnings for Luxor are suppressed.
evaluate (generic function with 1 method)
```

You can also see it in the latest CI build: https://github.com/JuliaGraphics/Luxor.jl/runs/5070187699?check_suite_focus=true#step:6:373

I think you just have to add MathTeXEngine to the Project.toml (just like LaTeXStrings, even though you're `@require`-ing them).

**Comment by mossr** [comment]
Actually, it looks like it's due to other packages loaded after Luxor that _themselves_ load LaTeXStrings or MathTeXEngine. I've posted about this here to track: https://discourse.julialang.org/t/project-toml-specification-for-packages-used-via-requires/14806/6

Adding MathTeXEngine to Luxor's Project.toml _will_ resolve this in the short-term, but as you said I think it completely misses the point of Requires... 🤷‍♂️

**Comment by davibarreira** [comment]
I mean... Is this actually a bug? Cause everything works... It's pretty much just an annoying warning. No?

**Comment by cormullion** [comment]
fixed by https://github.com/JuliaGraphics/Luxor.jl/pull/207 ?
