### ISSUE TITLE
How to rotate elements in a local coordinate system?

### ISSUE THREAD

**Issue by juliohm** [JuliaGraphics/Luxor.jl#20]
First of all, this is one of the most insanely good packages I have seen in Julia, awesome work!

I am trying to generate a logo for my GeoStats.jl package and so far this is what I have:

```julia
using Luxor

srand(2017)

# Julia colors
darker_purple = (0.584, 0.345, 0.698)
lighter_purple  = (0.667, 0.475, 0.757)
darker_green  = (0.22, 0.596, 0.149)
lighter_green  = (0.376, 0.678, 0.318)
darker_red  = (0.796, 0.235, 0.2)
lighter_red  = (0.835, 0.388, 0.361)

purples = (darker_purple, lighter_purple)
greens = (darker_green, lighter_green)
reds = (darker_red, lighter_red)

# Logo size
w = 800; h = 250
Drawing(w, h, "GeoStats.png")

# Draw axes
oᵥ = 10; oₕ = 30
translate(Point(oᵥ,oₕ))
axes()

# Draw random points
for i=1:300
    color = rand([purples, greens, reds])
    pos = Point(rand(10:w),rand(10:h))
    radius = 4
    sethue(color[1]); circle(pos, .65*radius, :fill)
    sethue(color[2]); circle(pos, .75*radius, :stroke)
end

# Draw ellipses
origin()
tiles = Tiler(w, h, 10, 10)
sethue("black")
for (pos, n) in tiles
    if n in [29]
        gsave()
        a = 100; b = 50
        sethue("black")
        ellipse(pos, a, b, :stroke)
        arrow(pos, pos + Point(a/2,0))
        arrow(pos, pos + Point(0,b/2))
        grestore()
    end
end

# Draw GeoStats.jl
origin()
translate(oᵥ, oₕ)
sethue("black")
fontsize(120); fontface("Georgia-Bold")
text("GeoStats.jl", halign=:center, valign=:middle)

# Save and preview
finish()
preview()
```
![logo](https://cloud.githubusercontent.com/assets/3345261/26229901/dcd6d88c-3bf9-11e7-9a96-0ba7d9921f9b.png)

I am using the tiles to loop over the logo and put an ellipse only at a few locations. I couldn't figure out a way to rotate the ellipses locally, how can I achieve this with Luxor.jl? If you have a more elegant way to draw ellipses at random in space with random orientation, I'd love to learn.

Also, I don't know how complicated would it be to replace the capital `S` in `GeoStats.jl` by a Bezier mimicking a river channel, something like this meandering river:
![meander](https://notendur.hi.is/~oi/Siberia%20photos/Meandering%20river%20on%20the%20Yamal%20tundra.jpg)

That would awesome, but I am happy just with the rotated ellipses :blush:

**Comment by cormullion** [comment]
Hi! Cool stuff!

More control is usually achieved by shifting the coordinate system, then treating the new location as the origin. So:

 ```
        gsave()
        translate(pos)
        rotate(rand(0:pi/12:2pi)) # <-  rotates about new origin
        a = 100; b = 50
        sethue("black")
        ellipse(O, a, b, :stroke)
        arrow(O, O + Point(a/2,0))
        arrow(O, O + Point(0,b/2))
        grestore()
```

Or write a function to do randomly rotated ellipses.. Perhaps:

```
randellipse(pos, w, h, action) = begin
    gsave()
    randomhue()
    translate(pos)
    rotate(rand(0:pi/12:2pi))
    ellipse(O, w, h, :stroke)
    grestore()
end

randpoint = [Point(rand(-400:400), rand(-250:250)) for i in 1:100]
randellipse.(randpoint, 20, 10, :stroke)
```

a bit more Julian?

Not too sure about the Bezier "S" — would it be better as a background?

![geostats-400](https://cloud.githubusercontent.com/assets/52289/26236090/7f7cd53e-3c66-11e7-8fe9-06837f45803b.png)

**Comment by juliohm** [comment]
Awesome! I was confused about the coordinate system, now it makes a lot of sense :+1: I will think about the background image, maybe it is too much for what I have in mind right now :blush:
