### ISSUE TITLE
How to find the current line thickness

### ISSUE THREAD

**Issue by StevenSiew** [JuliaGraphics/Luxor.jl#253]
When drawing lines, I can set the line thickness with

setline(4)

But for the life of me I could not figure out how to get the current line thickness. The reason I need this is because I have functions which draw lines for me and I need to check the current line thickness before I draw. If the current line thickness is WRONG then I remember the current line thickness and set it to the correct thickness value then draw my lines and then set it back to the previous value.

**Comment by cormullion** [comment]
http://juliagraphics.github.io/Luxor.jl/dev/explanation/luxorcairo/#Adding-Cairo-functions might help ...
