### ISSUE TITLE
Regression in opacity/hue settings in master?

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Luxor.jl#256]
I noticed a slight difference between the opacity/hue settings with the current master (3.7.0) and the current release (3.6.0).

```julia
using Luxor

@draw begin
background("midnightblue")

sethue("red")
circle(O, 150, :fill)

setopacity(0.5)
sethue("green")

box(O, 100, 400, :fill)
end 
```

3.7.0:

<img width="792" alt="Screenshot 2023-01-11 at 14 45 08" src="https://user-images.githubusercontent.com/52289/211836434-53c2509c-5b26-469d-96da-3ec5aad0b68a.png">

3.6.0:

<img width="824" alt="Screenshot 2023-01-11 at 14 46 48" src="https://user-images.githubusercontent.com/52289/211836466-606da624-373d-4ff7-83f0-f5ac42fa32a3.png">

@oheil - I think this might have been introduced when the color-setting code was refactored? I'd be grateful for your opinion!

**Comment by oheil** [comment]
Yes, the bug is in
drawings.jl
with default value for alpha channel in function
_set_current_color(r,g,b,a=1.0)
This is wrong.
There must be specific function
_set_current_color(r,g,b)
which doesn't change the alpha channel.

Do you want me do PR? Of course, but if not, just say...

**Comment by oheil** [comment]
I think I will produce some new tests for the latest bugs...
