### ISSUE TITLE
How can I recolor a graphic?

### ISSUE THREAD

**Issue by guo-yong-zhi** [JuliaGraphics/Luxor.jl#262]
I can change the size of an image with `translate` or `scale`. Is there any function like `colortranslate`or `colorremap` that can change the color of an image?

For example:
```julia
function resizesvg(svgdrawing; ratio=1)
    svgnew = Drawing(size(svgdrawing) .* ratio..., :svg)
    scale(ratio...)
    placeimage(svgdrawing)
    finish()
    svgnew 
end

function recolorsvg(svgdrawing, args...; kwargs...)
    svgnew = Drawing(size(svgdrawing)..., :svg)
    I_want_some_magic_here(args...; kwargs...)  # <---
    placeimage(svgdrawing)
    finish()
    svgnew
end
```
Any workflow suggestions?

**Comment by cormullion** [comment]
Interesting question. If you're creating the SVG in Luxor, you might be able to gain access to the text source, and - assuming that Cairo's SVG output is reasonably consistent - make text edits to the color definitions. It sounds like a hack, of course, but a fun one...  😂
