### ISSUE TITLE
Small circles does not have enough precision

### ISSUE THREAD

**Issue by hyrodium** [JuliaGraphics/Luxor.jl#268]
# MWE

```julia
using Luxor

@svg begin
    setline(0.1)
    for r in 1:10
        circle(Point(0, 0), r, action = :stroke)
    end
    sethue(1,0,0)
    rotate(deg2rad(22.5))
    for r in 1:10
        circle(Point(0, 0), r, action = :stroke)
    end
end 50 50 "b.svg"
```

Generated image:
![b](https://github.com/JuliaGraphics/Luxor.jl/assets/7488140/ac5323c5-0c71-4f57-91bc-8022f303fa99)

Magnified image:
![image](https://github.com/JuliaGraphics/Luxor.jl/assets/7488140/0a7b5d7d-3676-4348-85ce-41962c420529)

There are 10 circles in the image, and the small five circles does not have enough precision.

# Detail
There are four bezier segments for circles with a radius larger than 5, but if the radius is less or equal to 5, the number of segments will be two.

The following image is a screenshot with Inkscape.
![image](https://github.com/JuliaGraphics/Luxor.jl/assets/7488140/d2f5bda9-ecbf-40f2-a92b-eb3dd8a987f6)

I think this behavior is due to Cairo because the `circle` function just calls `Cairo.arc(_get_current_cr(), x, y, r, 0, 2pi)`.
https://github.com/JuliaGraphics/Luxor.jl/blob/375bb999e04f0ec5fcf14af82d5bd4188378bdc2/src/curves.jl#L3-L11

# How to fix
Update the definition of `circle` will solve the problem.
```julia
function circle(x::Real, y::Real, r::Real;
    action = :none)
    if action != :path
        newpath()
    end
    Cairo.arc(_get_current_cr(), x, y, r, 0, pi/2)
    Cairo.arc(_get_current_cr(), x, y, r, pi/2, pi)
    Cairo.arc(_get_current_cr(), x, y, r, pi, 3pi/2)
    Cairo.arc(_get_current_cr(), x, y, r, 3pi/2, 2pi)
    do_action(action)
    return (Point(x, y) - (r, r), Point(x, y) + (r, r))
end
```

![image](https://github.com/JuliaGraphics/Luxor.jl/assets/7488140/55eec4dc-da7e-422e-b814-6154efd7dc83)

If this fix is the right way, I'm happy to make a PR!

**Comment by cormullion** [comment]
Good idea! These circles are pretty small - I wonder whether the Cairo routines (https://github.com/ImageMagick/cairo/blob/main/src/cairo-arc.c might be the one) aren't so accurate for very small radii...

Anyway, your suggested code/fix looks good!

**Comment by cormullion** [comment]
@hyrodium I'm going to get another release out this week - do you want to make a PR for these circles?

**Comment by cormullion** [comment]
Cool! Thanks!
