### ISSUE TITLE
Using Interact.jl and Luxor.jl inside IJulia (Jupyter) notebook

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Luxor.jl#27]
The way to do interactive graphics is like this: 
```
using Interact, Luxor
@manipulate for x in 1:1000, r in 0:0.1:1, g in 0:0.1:1, b in 0:.1:1
    d = Drawing(300, 300, :svg)   # <-------------------------
    origin()
    sethue(Colors.RGB(r, g, b))
    box(O, x, x, :fill)
    finish()
    d  # <------------------------------
end
```

ie return the in-memory drawing. 

![screen shot 2017-11-27 at 15 55 55](https://user-images.githubusercontent.com/52289/33275753-8118190a-d38b-11e7-85a1-4cfdd270531b.png)

If you use the file-based method, it doesn't work (the sliders will be hidden). (https://github.com/JuliaGizmos/Interact.jl/issues/196)

There's something amiss with the interaction between IJulia, Jupyter, and Luxor, which should be addressed.

**Comment by stefan911** [comment]
Entropy reduction overtime has resolved this issue as works for me.
