### ISSUE TITLE
MethodError: objects of type String are not callable

### ISSUE THREAD

**Issue by omofolarin** [JuliaGraphics/Luxor.jl#272]
Please I’m trying out Luxor
@png begin
    text(“Hello world”)
    circle(Point(0, 0), 200, action = :stroke)
end
But I get this error:
┌ Error: Hint-handler #41 for MethodError in ImageCore caused an error
└ @ Base.Experimental experimental.jl:321
MethodError: objects of type String are not callable
Julia 1.9

**Comment by cormullion** [comment]
Hi! Luxor doesn't use Images, and that message is unrelated to anything in Luxor. Try again in a new Julia session, without having too many other packages in your current project.

**Comment by omofolarin** [comment]
Yes, it works. Thanks for the feedback
