### ISSUE TITLE
Remove dependency on Juno.jl

### ISSUE THREAD

**Issue by hyrodium** [JuliaGraphics/Luxor.jl#283]
Luxor.jl depends on Juno.jl, which is now deprecated.
This package can be added to `[weakdeps]` table, but I don't think this package is used in these days, so it should be just removed.

https://github.com/JuliaGraphics/Luxor.jl/blob/9bf75ac9d27b2be4b120693fd8cfae1dcda989e5/Project.toml#L14

This change will be breaking.

**Comment by cormullion** [comment]
Yes, I've been watching the Juno.jl page - it still says "maintenance and bug fixes only " rather than deprecated. But it can probably be removed and nobody will complain :)

**Comment by hyrodium** [comment]
>it still says "maintenance and bug fixes only " rather than deprecated.

Ah, thank you for the clarification!

**Comment by cormullion** [comment]
>"maintenance and bug fixes only " rather than deprecated

although I think it is kind of deprecated anyway... :)
