### ISSUE TITLE
SVG with transparent background

### ISSUE THREAD

**Issue by gpucce** [JuliaGraphics/Luxor.jl#286]
On Pluto It seems that when creating an svg with `@svg` I can't have it with transparent background. Neither without setting it nor setting it to transparent with `background(0, 0, 0, 0)`. I tried setting fill-opacity:0 by hand in the svg string and it works.

**Comment by cormullion** [comment]
Hi! This is described in the docs:

<img width="864" alt="Screenshot 2023-11-01 at 15 12 24" src="https://github.com/JuliaGraphics/Luxor.jl/assets/52289/e5f80cc1-8634-4a64-b29d-f779f7d88283">

and 

<img width="1157" alt="Screenshot 2023-11-01 at 15 11 07" src="https://github.com/JuliaGraphics/Luxor.jl/assets/52289/2c730162-7c58-4c41-b0a9-178ac3ed1350">

Actually the `@drawsvg` doesn't set the background for you, so you could use that. Hope this helps.

**Comment by gpucce** [comment]
Ah sorry I missed it, thank you so much!
