### ISSUE TITLE
[info] using Luxor in Gtk

### ISSUE THREAD

**Issue by nodrygo** [JuliaGraphics/Luxor.jl#29]
Just for info and fun    
I have created a little stupid demo for [Luxor in a Gtk canvas](https://github.com/nodrygo/GtkLuxorNaiveDemo)    

add unfinished  autonomous [AlarmClock](https://github.com/nodrygo/jAnalogAlarmClock)     

Thank's for Luxor witch is a very cool project

**Comment by cormullion** [comment]
Cool stuff! I’ll add a link to the docs soon!
