### ISSUE TITLE
A 1x1 box is semi-transparent

### ISSUE THREAD

**Issue by flexagoon** [JuliaGraphics/Luxor.jl#298]
It seems like the easiest way to paint a single pixel with Luxor.jl is like this:

```julia
box(p, 1, 1, :fill)
```

However, for some reason, this makes the box semi-transparent.

## Example:

```julia
@draw begin
	background("blue")
	sethue("white")
	for x in -150:150
		for y in -150:150
			p = Point(x, y)
			box(p, 1, 1, :fill)
		end
	end
end
```

Expected result:

![image](https://github.com/JuliaGraphics/Luxor.jl/assets/66178592/9d0768d7-fa43-429e-af68-ab968516c4a9)

Actual result: 

![image](https://github.com/JuliaGraphics/Luxor.jl/assets/66178592/a16587f8-5739-486a-b656-78816234bd29)

**Comment by flexagoon** [comment]
Applying each box twice (eg calling `box` two times with the same parameters) makes it appear correctly.

**Comment by cormullion** [comment]
Hi! I believe antiasliasing is on by default. So try:

```julia
setantialias(1)
```

which switches it off.

See [here](https://juliagraphics.github.io/LuxorManual/dev/explanation/perfectpixels/) for more.

**Comment by flexagoon** [comment]
@cormullion that does fix the issue, thank you!

By the way, is there a better way of painting individual pixels? The only two methods I managed to find is either drawing a 1x1 box or manually creating a pixel matrix before initializing the drawing. The first one is much easier, but as it turns out it requires disabling antialiasing.

**Comment by cormullion** [comment]
If you're going to be addressing pixels a lot, then you should probably be using Images.jl rather than Luxor.jl ...  The only benefit of Luxor's "imagematrix" feature is being able to combine both simple pixel-addressing (where an image is merely a Julia array) with vector graphics and text ... The conflicting coordinate systems are mildly irritating though 😀

**Comment by flexagoon** [comment]
Unfortunately I need both per-pixel drawing and vector shapes, so I can't really use Images.jl
