### ISSUE TITLE
Running @draw in a loop

### ISSUE THREAD

**Issue by j-adel** [JuliaGraphics/Luxor.jl#299]
Hello! I was wondering if there is a way to run one of the draw macros in a loop such that the preview window shows them sequentially. Currently, the only way I've found is through animate() which creates and shows a gif of a predetermined size. What I was thinking of is more similar to the draw window in Processing.org where the renders aren't stored and can run indefinitely. Thanks!

**Comment by cormullion** [comment]
Luxor is a bit static, and doesn’t provide a ‘live’ window to display a drawing. It is possible, though- see the docs here: https://juliagraphics.github.io/LuxorManual/dev/howto/livegraphics/ .

**Comment by j-adel** [comment]
Perfect! Thanks for the quick answer. I'd consider this issue closed then. Perhaps it would be a good idea to mention this option on the Make Animations page in the documentation?
