### ISSUE TITLE
passing more parameters in the Scene function

### ISSUE THREAD

**Issue by mantzaris** [JuliaGraphics/Luxor.jl#30]
When using the animate function, the array of Scenes; how can it be used to pass to the different function parameters to 'backdrop'/ 'frame' etc? I would like to pass in data computed in the iterative cycles which is stored in a composite type and although I am not sure this is the best way, to update the state I wish to pass the type through the function calls of each frame

**Comment by cormullion** [comment]
Hi there! I really appreciate your input about how this currently works - perhaps the design can be improved. (Surely it can!)

I’ve noticed the problem before (and it relates to the general theme about avoiding global variables in Julia code for performance reasons). One solution I’ve used before is to define a frame function that accepts keyword arguments, as well as the two obligatory arguments that must be defined. Then you call the frame functions like this:

`
Scene(moviename, (s, f) -> framefunc(s, f, kwarg1=“a”, kwarg2=“b”))
`
(I’ll have to check this syntax when I’m near a computer...)

**Comment by mantzaris** [comment]
What is the solution to having global variables? Can a formation of a module or struct work?

This code you wrote (s, f) -> drawframe(s, f, bigarray)) ,...looks interesting. Could you explain how this is working? Is it a use of 'dispatch' of a function to the correct most applicable method?

**Comment by cormullion** [comment]
This is using an anonymous function that takes two arguments which is defined to simply call another one that takes 3, thus splicing another argument in. What’s being passed is a function definition (I think). The problem being solved here is that you’re passing your new user-defined functions to an previously-defined and compiled function in Luxor that was written expecting any future functions to have two predictable arguments. 

I’ll have to read the section in the manual about scope and global variables again... I didn’t quite get it last time. ;)
