### ISSUE TITLE
Julia v1.11 internal changes 

### ISSUE THREAD

**Issue by cormullion** [JuliaGraphics/Luxor.jl#301]
The next release of Julia  - v1.11 - is currently available as `v1.11.0-alpha2`. ~~This is (as far as Luxor.jl is concerned) a **breaking** release; Luxor.jl won't create drawings at all if running on Julia v1.11.~~

This release includes internal changes to `IOBuffer`. It's possible that these cause some differences in Luxor code. If you're running on v1.11, check any output carefully...

~~If you should require to output drawings from Luxor.jl, you should keep a Julia v1.10 release around.~~

**Comment by j-adel** [comment]
Are there plans to be compatible with v1.11?

**Comment by cormullion** [comment]
> Are there plans to be compatible with v1.11?

Not yet! 😀
