### ISSUE TITLE
Can luxor use `latex formulas` ?

### ISSUE THREAD

**Issue by davidbp** [JuliaGraphics/Luxor.jl#32]
Hello,

I have seen some amazing vector drawings in `luxor` that include `text`.
Nevertheless I have not seen in the docs any example involving formulas (or latex expresisons).
Is it possible to embbed latex formulas in luxor? 

For example could we write $\pi r^2$ inside a circle?

Something like this:

```julia
@png begin
        fontsize(20)
        circle(O, 100, :stroke)
        text(" \pi r ^2", halign=:center, valign=:middle)
       
       # I would like to have something like this? 
       # latex("$ \pi r^2$", halign=:center, valign=:middle)
     end
```

I have seen that one of you videos uses some formulas [video](https://www.youtube.com/watch?v=iBrpZ7vn_Mw). Is the code for this animation available? I'm not sure if it uses fancy `unicode` letters like `\theta` or we can use more complication latex expressions such as `\sum_{i \in X} \frac{\theta_i}{\pi^2}` (which I just made up and does not mean anything).

It would be awesome if you could make public some of the code you used for some of your  youtube animations. It would probably inspire people to try more your package.

**Comment by cormullion** [comment]
Hi! Well, Cairo doesn't do LATEX (installation would be even more difficult if it had to install a fully working TEX system), but there's a hint of it in the PANGO markup routines used by Cairo's pro text interface. I haven't looked into these very much, other than to write some documentation, so I've just got this:

```
settext("<span font='26' background ='green' foreground='red'> Hey</span>
    <i>italic</i> <b>bold</b> <sup>superscript</sup>
    <tt>monospaced</tt>",
    halign="center",
    markup=true,
    angle=10)
```

and this is slightly broken in Cairo.jl anyway... (https://github.com/JuliaGraphics/Cairo.jl/issues/201) :)

- so if you use the Pro text API, you can at least do superscripts (I think).

I usually post some source code as gists usually (https://gist.github.com/cormullion) but don't bother for the ones that are too large, too stupid, or too embarassing...

In that animation, the symbols are placed "by hand". I don't mind doing it once or twice, but generally avoid formulae.

I didn't know about Asymptote before starting work on Luxor; perhaps I would be using that now had I known about it. See https://github.com/sswatson/AsyPlots.jl for a recently developed Julia interface.
