### ISSUE TITLE
multithreading error: `There isn't a current drawing`

### ISSUE THREAD

**Issue by guo-yong-zhi** [JuliaGraphics/Luxor.jl#321]
I found that Luxor's multithreading feature does not work well in Pkg test mode. The same code works well in my REPL (sometimes). I am not sure that if this is related to the test mode or the environment.
Additionally, it seems that everything works well on Windows, but not on Linux.
The minimum reproducing code: https://github.com/guo-yong-zhi/WordCloud.jl/blob/multithread_debug/test/runtests.jl
The error message (CI): https://github.com/guo-yong-zhi/WordCloud.jl/actions/runs/11340408881/job/31536783739

The way to reproduce:
1. Clone the repo and checkout to the branch `multithread_debug`
2. Run `cd WordCloud.jl`
3. Run `julia -t 4`
4. Run `] dev .`
5. Run `] test WordCloud`

@cormullion @oheil

**Comment by cormullion** [comment]
Thanks for the report. Someone who understands multithreading (ie not me) might be able to investigate.

**Comment by oheil** [comment]
I will have a look, my time is very short, but I hope for next weekend or the next...

**Comment by oheil** [comment]
As easy the solution seems, it took me the whole sunday to find ;-)
