### ISSUE TITLE
How to get the bounding box of a **rotated** text?

### ISSUE THREAD

**Issue by guo-yong-zhi** [JuliaGraphics/Luxor.jl#325]
`BoundingBox(str::AbstractString)` and `textextents` take a string as input and return the box info about the text. However, what I need is the bounding box of a rotated text (e.g. generated by `settext(str, O; angle=angle)`).
Let me explain the background:
**My goal** is to draw a text with a certain angle in a minimal size bitmap image.
Currently, the following steps are implemented:
1. started with a big enough Drawing():
`Drawing(bigsize, bigsize, :image)`
2. draw the text with the desired angle:
`settext(str, O; angle=angle)`
3. convert it to a bitmap image with 
`image_as_matrix()`
4. crop the pixel matrix with [a native algorithm](https://github.com/guo-yong-zhi/WordCloud.jl/blob/master/src/rendering.jl#L65):
`find_empty_pixels_on_border_and_crop(img)`

The problem is that the 3rd step, `image_as_matrix()`, takes a lot of time if the `Drawing` is big, despite there are many empty pixels in it. 
So I want to **get the bounding box of the rotated text (or all the content of a Drawing)**, and then crop and resize the `Drawing` before the `image_as_matrix()`. 
Perhaps, there is a different and more efficient way to achieve my goal. Please let me know.

**Comment by cormullion** [comment]
You might be able to do something with `textoutlines()`

```julia
@draw begin    
    txt = "Hello world"
    angle = rand(0:2π)
    fontsize(40)

    @layer begin
        rotate(angle)
        textoutlines(txt, O, action=:path)
        p = storepath()
        bx = box(BoundingBox(p))
        pts = getworldposition.(bx)
        newpath()
    end

    wbx = BoundingBox(pts)
    box(wbx, :stroke)

    @layer begin
        rotate(angle)
        text(txt)
    end
end
```

Unfortunately you'll come up against the "two text APIs" situation, where the various text APIs in Cairo/Luxor aren't very functional.. 🙁

**Comment by guo-yong-zhi** [comment]
It works. However, `textoutlines` and `textpath` are "Toy APIs". I fond the pro version api `cairo-glyph-path` in cairo, but it's not in Cairo.jl  :(
>Note: The [cairo_text_path()](https://www.cairographics.org/manual/cairo-Paths.html#cairo-text-path) function call is part of what the cairo designers call the "toy" text API. It is convenient for short demos and simple programs, but it is not expected to be adequate for serious text-using applications. See [cairo_glyph_path()](https://www.cairographics.org/manual/cairo-Paths.html#cairo-glyph-path) for the "real" text path API in cairo.  _(from www.cairographics.org)_

**Comment by cormullion** [comment]
There are some open Cairo.jl Pull Requests with code for more support for ‘glyphs’. It would be possible to add these to your own projects if you needed the functionality now.  Cairo isn’t maintained much these days. ..

An alternative to consider is Makie.jl, which has support for font glyphs (as far as I know).
