### ISSUE TITLE
Taxonomy

### ISSUE THREAD

**Issue by CiaranOMara** [JuliaGraphics/Luxor.jl#43]
There is a taxon issue regarding the turtle emoji used in the documentation. The Turtle emoji is a Tortoise. This issue may need to be reported upstream. Also, I'm pretty sure that the Teenage Mutant Ninja Turtles were in fact Tortoises.

https://www.youtube.com/watch?v=EEMMShaYcNA

Please feel free to close this issue.

**Comment by cormullion** [comment]
:) 

I think this is more of an OS-related problem (https://emojipedia.org/turtle). I can only test on Apple's platforms; more testing on other platforms would be helpful... :)
