### ISSUE TITLE
Using function Base.display in preview()

### ISSUE THREAD

**Issue by simonschoelly** [JuliaGraphics/Luxor.jl#46]
Currently, if a user does not use Juypter or Juno, then `preview()` tries to display the drawing in an external program. This makes it impossible to use other IDE's and notebooks that provide image drawing capabilities. 

There is a solution for that by using the functions `displayable(mime)` and `display(mime, x)`, that verify if the environment allows drawing a certain mime type and then draw that.

If such a thing is welcome in Luxor, I could submit a PR for that.

**Comment by cormullion** [comment]
Hey @simonschoelly ! I dont understand any of this display stuff, I usually just ask @pfitzseb to help me. :) If you can do anything to improve it here, go for it!

**Comment by cormullion** [comment]
Also:

 "the way this should be handled is by defining a new Display and display method that handles the svg opening stuff" (pfitzseb) 

and

"search for GadflyDisplay in https://github.com/GiovineItalia/Gadfly.jl/blob/34b4f348f04214e231078eb82edb2c2fbc180d60/src/Gadfly.jl"

This is too complicated for me, so it's a job waiting for a knowledgeable contributor.

**Comment by simonschoelly** [comment]
I dont exactly remember what my issues last time, but I just checked that it works perfectly well to use the `@draw` and `@svg` macros, so there is probably no reason to leave this open.

**Comment by cormullion** [comment]
Hi! Thanks again. There are still issues with the display system (if you're using VSCode) but there have been a few improvements as well.
