### ISSUE TITLE
Support for LaTeX strings

### ISSUE THREAD

**Issue by Roger-luo** [JuliaGraphics/Luxor.jl#51]
Does Luxor support LaTeX Strings? Any idea how to support it?

This doesn't work (as expected)

```
using Luxor, LaTeXStrings

@png begin
       fontsize(30)
       text(L"\alpha", O, halign=:center, valign=:middle)
end
```

**Comment by cormullion** [comment]
I think you've asked this before... :) (https://github.com/JuliaGraphics/Luxor.jl/issues/32) 

If you use the Pro text interface, some of these will work. If you use the Toy text interface, few of them will... 

If Cairo/Luxor had decent Pango support, of course... :)

**Comment by Roger-luo** [comment]
Err, sorry, I guess this might be a solution:

https://github.com/SimonDanisch/UnicodeFun.jl
