### ISSUE TITLE
Ellipse angle

### ISSUE THREAD

**Issue by Ryngetsu** [JuliaGraphics/Luxor.jl#54]
Hello, it's the first time I'm using Luxor and even Julia. I managed to draw an ellipse for the minimal instance of the project I'm doing, but it seems like it has an angle which shouldn't be there. I don't know if I'm being understandable.

Here's the portion of the code that draws to a png file:

    for ellipse in env.ellipses
        semiFocusDist = sqrt(ellipse.semiBigAxe^2 - ellipse.semiLittleAxe^2)
        f = Point(ellipse.center[1] - semiFocusDist, ellipse.center[2])
        f2 = Point(ellipse.center[1] + semiFocusDist, ellipse.center[2])
            
        @show f
        @show f2

        f = rotatePointAroundPoint(f, ellipse.center, ellipse.rotationAngle)
        f2 = rotatePointAroundPoint(f2, ellipse.center, ellipse.rotationAngle)
        
        @show f * scale
        @show f2 * scale
        
        sethue("yellow")
        Luxor.ellipse(f * scale, f2 * scale, 2 * ellipse.semiBigAxe * scale, :fill)

        sethue("black")
        Luxor.circle(f2 * scale, circleSize, :fill)
        Luxor.circle(f * scale, circleSize, :fill)
    end

I also drawed the focus points of the ellipse for debugging purposes.

So, my ellipse type has a rotationAngle field, and for this ellipse, it's zero.

Here's the console output:

>Loading instance:
        Width : 1
        Height : 1
        Robot starting position : (0, 0)
        Objective position : (1, 1)
        Speed in water : 3.0
        Speed in oil : 4.0
        Ellipse n° 1 Center : (0.5, 0.5), Axes : 0.3 and 0.4, Angle : 0.0
f = Point(0.23542486889354086, 0.5)
f2 = Point(0.7645751311064591, 0.5)
f * scale = Point(235.42486889354086, 500.0)
f2 * scale = Point(764.5751311064591, 500.0)
Solution time: 5.121320343559643 units of time.
  2.534168 seconds (5.75 M allocations: 285.122 MiB, 5.16% gc time)>

You can see that the two focus points have the same y, thus the ellipse should be horizontal, but here's the png file:

![test](https://user-images.githubusercontent.com/25417373/57185411-2e8e3980-6ecb-11e9-98e1-39c589fa8e0e.png)

Thanks for looking into this.

**Comment by Ryngetsu** [comment]
After looking at the source code, I think it's related to this:

`
    function ellipse(focus1::Point, focus2::Point, k, action=:none;
                     stepvalue=pi/100,
                     vertices=false,
                     reversepath=false)
`

and specially

`phi = slope(O, focus2) # angle between the major axis and the x-axis`

Shouldn't it be slope(focus1, focus2)?

**Comment by Ryngetsu** [comment]
Well sorry to fix it that fast, but it was that line 😄  . I changed it and here's the outcome:

![test](https://user-images.githubusercontent.com/25417373/57185511-0dc6e380-6ecd-11e9-995c-35814ca73ce1.png)

Perfectly balanced, as all things should be.

**Comment by cormullion** [comment]
Hi there! Thanks so much for looking into it! I’m sorry that you’ve discovered one of my many geometrical errors...😂  but it should be easy to fix! You can make a pull request? Or I can fix it next week.

**Comment by Ryngetsu** [comment]
Done.

About pull requests, I did it by forking and changing my repository, but can I do it without forking? I'm still kinda new to git.

**Comment by cormullion** [comment]
I think you're supposed to fork it on GitHub, pull it to your local machine, make a branch, do the changes, commit, push to GitHub, and make a pull request... I'm hopeless with git, I know about 6 commands and stick with them. :)
