### ISSUE TITLE
Reproducing Sample Image

### ISSUE THREAD

**Issue by tawheeler** [JuliaGraphics/Luxor.jl#59]
The basics.md file has an example for IJulia:
```julia
Drawing()
origin()
setopacity(0.5)
for θ in range(0, π/6, 12)
    randomhue()
    gsave()
    squircle(Point(200cos(θ), 200sin(θ)), 130, 130, :fillstroke, rt=2.5)
    grestore()
end
finish()
preview()
```

In order to match the output and not err out, I had to change the range call to:
```julia
for θ in range(0, stop=2π*11/12, length=12)
```

**Comment by cormullion** [comment]
oh, yes, that’s been changing for the last few versions... What version does it fail on?

**Comment by tawheeler** [comment]
Thanks! I am on julia 1.1.1

**Comment by cormullion** [comment]
Now fixed on master. Thanks for spotting this. 

Who knows when a new release of Luxor will be possible... :)
