### ISSUE TITLE
Integer division error in Partition

### ISSUE THREAD

**Issue by BeastyBlacksmith** [JuliaGraphics/Luxor.jl#64]
The following `Partition` can be constructed but not collected:
```julia
julia> p = Partition(0.0, 59.99700000000001, 9.969619777722377, 9.969619777722377)
Partition(0.0, 59.99700000000001, 9.969619777722377, 9.969619777722377, 6, 0, 1, 1)

julia> collect(p)
ERROR: DivideError: integer division error
```

**Comment by cormullion** [comment]
Nice one... ! Fixed by  https://github.com/JuliaGraphics/Luxor.jl/commit/e1625d1ceda1b37f57dc5a560724394e84413e28 

There are very few checks in Luxor for silly input; :) perhaps I should add them, but it's kind of boring work... 😴

**Comment by BeastyBlacksmith** [comment]
Does this error for every `Partition` that is smaller than `3x3`?
Personally I would only error, if either `nrows` or `ncols` is equal to zero.
