### ISSUE TITLE
small bug

### ISSUE THREAD

**Issue by zahachtah** [JuliaGraphics/Luxor.jl#66]
I was playing with your very nice noise function

you need to change  (line 16) in the noise.jl

initsimplexnoise(seed)

to 

initnoise(seed)

the above function does not exist

**Comment by cormullion** [comment]
Hi! well spotted! Thanks... looks like a left-over from the transition from the old patented one to the new one.

**Comment by cormullion** [comment]
Should be fixed by https://github.com/JuliaGraphics/Luxor.jl/commit/5520bfdd320ace6824983d0406ed4a02cf69a37c
