### ISSUE TITLE
"uses of it in module Main must be qualified"

### ISSUE THREAD

**Issue by glwhart** [JuliaGraphics/Luxor.jl#67]
This is perhaps a noob question. I tried several of the examples and I get errors like the following. I don't know what they imply.

```
julia> text("hello world")
WARNING: both Luxor and Plots export "text"; uses of it in module Main must be qualified
ERROR: UndefVarError: text not defined
```

```
julia> @png begin
           sethue("red")
           randpoint = Point(rand(-200:200), rand(-200:200))
           circle(randpoint, 2, :fill)
           sethue("black")
           foreach(f -> arrow(f, between(f, randpoint, .1), arrowheadlength=6),
               first.(collect(Table(fill(20, 15), fill(20, 15)))))
       end
WARNING: both Luxor and Plots export "arrow"; uses of it in module Main must be qualified
ERROR: UndefVarError: arrow not defined
```

Sounds like I'm missing a module, or have a clash two different modules, but I'm not really sure. Can you give me any advice?

**Comment by cormullion** [comment]
Hi Gus. This is caused I think because you did `using` on two modules that export the same method name. If you want to use both modules at the same time, put a prefix of the module name and a dot before the function. (“Qualifying it”). Quite a common thing, I think. (E.g. https://github.com/JuliaPlots/Plots.jl/issues/2101)

**Comment by glwhart** [comment]
Thanks for the quick response. Your comment is spot on. The confusing thing is that this happens in a fresh REPL where I have not explicitly done a `using Plots`. So `Plots` must be loaded automatically with the new instance of Julia. Not sure if that behavior is because of some custom change I made (and forgot about) or what.

Thanks again.
