### ISSUE TITLE
Data in Animate and Double Pendulum Example

### ISSUE THREAD

**Issue by OctogonalWheel** [JuliaGraphics/Luxor.jl#69]
Hi I'm a newcomer to Luxor and Julia for that matter and I was wondering if there might be a more robust way to pass data into Animate other than defining an anonymous function inside the Scene call in Animate. Maybe an additional keyword argument? Also, if you have any tips on how I could clean up this double pendulum code I wrote it would be much appreciated.

```julia
using Luxor, DynamicalSystems, DelayEmbeddings
let
dp = Systems.double_pendulum([π/2, 0, 0, rand()],G=10.0, L1=1.0, L2=1.0, M1=1.0, M2=1.0)

t_sol = trajectory(dp, 5)

function frame(scene, framenumber, t_sol)
    i = framenumber
    background("white")

    w, x, y, z = columns(t_sol)
    origin = Point(0, 0)
    m1pos = Point(200*sin(w[i]), 200*cos(w[i]))
    m2pos = Point(200*(sin(y[i])+sin(w[i])), 200*(cos(y[i])+cos(w[i])))

    sethue("black")
    m1 = circle(m1pos, 2, :fill)
    m2 = circle(m2pos, 2, :fill)

    sethue("blue")
    pen1 = line(origin, m1pos, :stroke)
    pen2 = line(m1pos, m2pos, :stroke)

end

demo = Movie(1000, 1000, "double_pendulum", 1:size(t_sol, 1))

Luxor.animate(demo,[
    Scene(demo, (s, f) -> frame(s, f, t_sol),
        optarg=t_sol, 1:size(t_sol, 1))
    ],
    creategif=true, pathname = string(pwd(), "/pendulum.gif"))

end
```

**Comment by cormullion** [comment]
Hi there! Thanks for the interest in this little project! I'm not sure about the meaning of "more robust" here though...

Anyway, your code looks fine to me (I'm not an expert anyway) but I suppose there are some small tweaks that could be made:

```

function frame(scene, framenumber)
    i = framenumber
    background("white")
    t_sol = scene.opts                         # get opt arg
    w, x, y, z = columns(t_sol)

    m1pos = Point(200sin(w[i]), 200cos(w[i]))         # Julia syntax :)
    m2pos = Point(200(sin(y[i]) + sin(w[i])), 200(cos(y[i]) + cos(w[i])))

    sethue("black")
    circle.((m1pos, m2pos), 2, :fill)                   # broadcasting is cool
    
    sethue("blue")
    pen1 = line(O, m1pos, :stroke)                      # O is the origin
    pen2 = line(m1pos, m2pos, :stroke)
end

function main()
    dp = Systems.double_pendulum([π/2, 0, 0, rand()], G = 10.0, L1 = 1.0, L2 = 1.0, M1 = 1.0, M2 = 1.0)
    t_sol = trajectory(dp, 1)
    demo = Movie(1000, 1000, "double_pendulum", 1:size(t_sol, 1))
    animate(demo, [
        Scene(demo, frame, optarg = t_sol, 1:size(t_sol, 1))          # use optarg
        ], creategif = true, pathname = pwd() * "pendulum.gif")
end

main()
```

**Comment by OctogonalWheel** [comment]
I guess what I meant by "more robust" was that I thought the anonymous function call as the recommended way of passing in data in the animation documentation was kind of clunky. I think optarg was what I was looking for.

Thanks for all of your helpful edits to my code and for maintaining this awesome project. I just transitioned from python if you can't tell and I'm trying to break my old habits :). 

Also if I may ask, I was wondering how I would get those cool fading paths you made in your pendulum demo. Was it just a bunch of curves drawn between the last few points with a scaled opacity?

**Comment by cormullion** [comment]
Ah, I see. Anonymous functions are quite highly regarded in Julia (at least, since they became as quick as named functions...) but perhaps different languages have a different emphasis. But you're right, the options argument was added by someone who felt the same as you! :)

Re fading paths - I think there's a gist for that too - https://gist.github.com/cormullion/1fe11ac43375249939017fd16016476d.

Thanks!
