### ISSUE TITLE
Compatibility with Cairo 0.8+?

### ISSUE THREAD

**Issue by yha** [JuliaGraphics/Luxor.jl#75]
I found that I need to downgrade Luxor in order to use the newest version of Cairo (JuliaGraphics/Cairo.jl#310).
For my use case, Luxor 0.1.7 seems to work fine with Cairo 1.0.1 (but I only use Luxor for geometrical predicates, which I don't think actually use Cairo).
Should Cairo versions 0.8 and 1.0 be allowed in `Project.TOML`?

**Comment by cormullion** [comment]
Yes, welcome to the new world of Pkg compatibility... :) I didn't know the Cairo folks had got to version 1.0... I’ll upload another version tomorrow.

**Comment by cormullion** [comment]
Should be fixed now, with release 1.9. Let me know if you have problems... Sorry.. :)
