### ISSUE TITLE
Automatically generate the curves for letters in the Julia logo

### ISSUE THREAD

**Issue by mohamed82008** [JuliaGraphics/Luxor.jl#78]
Hi!

Thanks for the amazing package! I am trying to create a variation of the Julia logo with "turing" instead of "julia" for [Turing.jl](https://github.com/TuringLang/Turing.jl). So I was wondering if there is a way to automatically generate the curves used in `julialogo` to then generalize it to other letters. Thanks!

**Comment by cormullion** [comment]
Hi! Well, there's quick and dirty:

```
using Luxor

@draw begin
    fontface("MyanmarMN-Bold")
    fontsize(50)
    text("Turing", O)
    translate(100, -40)
    juliacircles(10)
end
```

<img width="203" alt="Screenshot 2020-01-02 at 19 23 48" src="https://user-images.githubusercontent.com/52289/71687299-6a004100-2d95-11ea-93c9-2af08cab72bb.png">

but that's cheating (or at least, guessing), and I know we would all want it to more calculated... :)

**Comment by mohamed82008** [comment]
Nice! I can perhaps draw each letter individually and do some translations to get it to look better. Thanks a lot for the starter!

**Comment by cormullion** [comment]
This code shows how you can break the text down into polygons:

```
function main()    
    @draw begin
        fontface("MyanmarMN-Bold")
        fontsize(50)
        sethue("black")
        text("Turing")
        textoutlines("Turing", O, :path)
        tpath = pathtopoly()
        newpath()
        sethue("red")
        xpoint = 0
        ypoint = Inf
        xpoint = polycentroid(tpath[4]).x
        for t in tpath
            cpos = polycentroid(t)
            (cpos.y < ypoint) && (ypoint = cpos.y)
        end
        rule(Point(xpoint, ypoint))
        rule(Point(xpoint, ypoint), π/2)
    end
end

main()
```

but it's a bit clumsy - you have subpaths with holes that have to be reversed... Have fun!

**Comment by mohamed82008** [comment]
Cool! Thanks a lot!
