### ISSUE TITLE
readpng should error on invalid inputs?

### ISSUE THREAD

**Issue by aviks** [JuliaGraphics/Luxor.jl#81]
If  `readpng` is passed a filename that does not exist, the still returns a CairoContext object. the pointer is non-zero, but the height and width are zeros. 

It may be useful to throw an exception is the file is non-existent?

**Comment by cormullion** [comment]
Yes, I've been putting off doing things like that! 😂 (sorry)

**Comment by aviks** [comment]
No worrries, not a big deal. Just thought I'd document this while I remember.

**Comment by cormullion** [comment]
Hopefully fixed in v1.11.0.
