### ISSUE TITLE
rule & BoundingBox bug?

### ISSUE THREAD

**Issue by dietercastel** [JuliaGraphics/Luxor.jl#83]
While playing around with Luxor I stumbled upon a possible bug.

Below is the code 
```
using Luxor
Drawing()
function bissect(p1,p2,p3,hue,bb)
    s1 = slope(p3,p2)
    s2 = slope(p1,p2)
    mins = min(s1,s2)
    maxs = max(s1,s2)
    half = (maxs-mins)/2
    sethue(hue)
    println(p2)
    newbb= BoundingBox([p2,boxmiddlecenter(bb)])
    println(newbb)
    rule(p2,mins+half,boundingbox=newbb) # Doesn't work
    #rule(p2,mins+half,boundingbox=newbb+1) # This works
end

origin()
r1 = rect(Point(0,0),200,200,:stroke)
bb1 = BoundingBox(r1)
sethue("blue")
# b[3] & b[4] don't exist
btl = boxtopleft(bb1)
btr = boxtopright(bb1)
bbr = boxbottomright(bb1)
bbl = boxbottomleft(bb1)
bissect(btl,btr,bbr,"purple",bb1) #shown
bissect(btr,bbr,bbl,"orange",bb1) #shown
bissect(bbl,btl,btr,"cyan",bb1) #shown
bissect(bbr,bbl,btl,"green",bb1) # not shown

finish()
preview()
```
This generates the following image:
![Screenshot 2020-03-02 at 19 29 21](https://user-images.githubusercontent.com/2487783/75708658-8818ed80-5cc1-11ea-8170-29e1bba085a2.png)

When i change `rule(p2,mins+half,boundingbox=newbb)` to `rule(p2,mins+half,boundingbox=newbb+1)` the green line IS drawn (and all of them have a bit of spillover).

When I looked at the implementation of rule I stumbled upon this TODO which might be a lead as to why this happens:
https://github.com/JuliaGraphics/Luxor.jl/blob/05e956bbcf5f74d17340c13585eada6f5ff55dee/src/basics.jl#L394

It's also curious that it doesn't happen in the 3 other cases. Maybe it's some off-by one error? If I have some more time I might delve deeper into the implementation myself but until then I'm interested in other thoughts about it and/or fixes.

**Comment by cormullion** [comment]
Hi Dieter - thanks for reporting this! I'll take a look tomorrow. It's almost certain that there are bugs in this code; I remember struggled to get it working for the simple cases, but there are many corner cases too. I definitely remember regretting that I ever started making the `rule` function do more than the basics... 😂

**Comment by cormullion** [comment]
Well, this is a fun bug, caused by me not understanding how Julia sets work... Apparently:

```
julia-1.4> s = Set{Point}()
Set{Point} with 0 elements

julia-1.4> push!(s, Point(0.0, 200.0))
Set{Point} with 1 element:
  Point(0.0, 200.0)

julia-1.4> push!(s, Point(100.0, 100.0))
Set{Point} with 2 elements:
  Point(0.0, 200.0)
  Point(100.0, 100.0)

julia-1.4> push!(s, Point(-0.0, 200.0))
Set{Point} with 3 elements:
  Point(0.0, 200.0)
  Point(100.0, 100.0)
  Point(-0.0, 200.0)
```

where I was assuming that the first and last points would be the same, but that `-0.0` vs `0.0` thing is sufficient to make the whole set thing not work.

I'm replacing it with a more basic array, and defining a version of `unique` that works with points.

**Comment by cormullion** [comment]
was closed for some reason, sorry. Anyway, you could see if the latest master has fixed this problem, and not introduced any new ones...

**Comment by dietercastel** [comment]
That seemed to solve the issue indeed as you can see below:

![luxor-drawing](https://user-images.githubusercontent.com/2487783/75997933-5e013e80-5f00-11ea-91b7-c61981d9856c.png)

**Comment by cormullion** [comment]
Cool. Thanks for the testing!
